### ISSUE TITLE
modify netCDF files

### ISSUE THREAD

**Issue by gvali** [Alexander-Barth/NCDatasets.jl#1]
Great work producing netCDF library for "julia"! 

Is it possible to add possibility to modify existing files? At the moment there are two modes:
'c' - create
'r' - read
It would be great to have an option 'a' similar with Python's netCDF4, which gives user an opportunity to modify the file. 
Sorry for starting an "issue", whereas it is more an request for future release...

**Comment by Alexander-Barth** [comment]
Thank you for your encouragement! Of course, it would be very helpful being able to append to an existing file. I just implemented the mode "a" in commit 4ce8ece.
Let me know if this is OK for you.

**Comment by gvali** [comment]
Superb! Thanks for enabling this so quickly...

Nevertheless, there is one issue: if I want to change existing variable, then I get an error:
ERROR: LoadError: NCDatasets.NetCDFError(-38, "NetCDF: Operation not allowed in data mode")

If I generate a variable beforehand, then I can change the values of both variables (new one and already existing one).

I can leave my test script. Currently, it is working, but if you comment the lines #29 and #32, then it does not work.

[test_netcdf.jl.zip](https://github.com/Alexander-Barth/NCDatasets.jl/files/1346748/test_netcdf.jl.zip)

**Comment by Alexander-Barth** [comment]
Thanks a lot for your test script. It helps a lot in fixing a bug. Indeed, the NetCDF file was not in the right mode when it was open with the option "append". It is fixed now.

A added a variant of your script to my unit tests to ensure that this will continue to work in future version.

Does it work now for you as well?

**Comment by gvali** [comment]
It is working for me as well! 

Thanks again for quick improvement and good luck keeping up great work!
