### ISSUE TITLE
Feature request: indexing datasets with symbols?

### ISSUE THREAD

**Issue by ali-ramadhan** [Alexander-Barth/NCDatasets.jl#101]
I don't know much about how the NetCDF C library works but right now you must index the dimensions and variables of an `NCDataset` with a string, e.g. `ds["time"]` and I was wondering if it would be possible to allow indexing via symbols, e.g. `ds[:time]`?

Is it as easy as dispatching like
```julia
getindex(ds::AbstractDataset, sym::Symbol) = getindex(ds, string(sym))
```
?

cc @glwagner

**Comment by visr** [comment]
Sounds good to me. Note that a ccall that expects a Cstring argument will happily accept either String or Symbol, so it should just be a matter of widening signatures to include symbols, no need for conversion.

**Comment by Alexander-Barth** [comment]
I guess, string indexing needs to stay because it is easier to handle variable names with space (or operators) in them or composed of a prefix and suffix (but is also possible with Symbols). So we should support both ways, string and symbol indexing? Would the user code not start to look ugly/confusing if they start to mix string and symbol ? Or is it upon the user to be consistent  ?

**Comment by visr** [comment]
Yeah AbstractString indexing definitely needs to stay, so we'd have to support both ways. I think the consistency here would indeed be up to the user. We could be consistent and always use string in the docs for instance.

This has precedence with [DataFrames.jl indexing](https://juliadata.github.io/DataFrames.jl/stable/lib/indexing/). Internally they use this in the type signatures:

```julia
const SymbolOrString = Union{Symbol, AbstractString}
```

**Comment by Alexander-Barth** [comment]
Thanks @visr, `SymbolOrString` trick seems to work here as well. But I realize now we probably need to allow symbols also for attribute, group and dimension names too.

**Comment by Alexander-Barth** [comment]
An alternative idea is to use symbols for query a NetCDF variable by standard name (CF convensions).

For instance if you have a variable with the poetic name `zos` in a NetCDF file and which has the following attributes:

```
zos (112 × 61 × 2)                                                                                                                                                   
  Datatype:    Float32                                                                                                                                                
  Dimensions:  lon × lat × time                                                                                                                                       
  Attributes:                                                                                                                                                         
   _FillValue           = 1.0e20                                                                                                                                      
   standard_name        = sea_surface_height_above_geoid                                                                                                              
   coordinates          = time lat lon                                                                                                                                
   long_name            = sea surface height                                                                                                                          
   units                = m                                                                                                                                           
   missing_value        = 1.0e20                                                                                                                                      
   _ChunkSizes          = Int32[1, 380, 1287]        
```

Then one could query the variable by `ds[:sea_surface_height_above_geoid]`. The netCDF variable names are not standardized, but querying a file by the `standard_name` attribute allows to reuse the same code for different NetCDF files (assuming they are following the CF conventions).

There could be different NetCDF variables with the same `standard_name` (for instance forecast `temperature` and analysis `temperature`). In this case, we need to decide: 1) an error or 2) a just warning a pick the first variable.

**Comment by visr** [comment]
I think this could be a nice functionality, finding variables by attribute values. But perhaps putting that into `getindex` is a bit too surprising. In general the same function should not do something completely different in two different methods. I believe this feature request comes from expecting/hoping to use symbols exactly the way that strings are used now.

**Comment by Alexander-Barth** [comment]
ok, calls like  `ds[:time]` should work in version 0.11. Fell free to reopen this issue if not.
