### ISSUE TITLE
attempt to transform dimensional information to Ranges instead of Vectors?

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#103]
By default, dimensional information is output by NCDatasets as Julia vectors. However, almost always the dimensional information can be compacted into ranges. E.g. instead of giving 
```
44-element Array{Int64,1}:
 -86
 -82
 -78
 -74
 -70
 -66
 -62
 -58
 -54
 -50
 -46
 -42
   ⋮
  46
  50
  54
  58
  62
  66
  70
  74
  78
  82
  86
```
as latitudes, we could instead give `-86:4:86`. Seems that it is easy to check whether it is possible to convert to a range by checking if `x = unique!(diff(values))` has length 1. If yes, a range can be made with step the value of `x[1]` and start and end the start and end of the data.

Having ranges instead of vectors can lead in performance increase in packages downstream, e.g. ClimateBase.

**Comment by Alexander-Barth** [comment]
Assume that the data is the vector `[1,2,3,4,5,7,8.8,9.9]`, then `v[1:3]` can be compressed as a range but not `v[6:8]`. So the output type is different for the particular indices. So one would need to load the complete vector (some vectors can be quite long, even 1D; or split accord different files for multi-file dataset) to verify that all elements of a  vector are indeed consecutive.

**Comment by Datseris** [comment]
I've already done this in ClimateBase.jl anyways. I was only referring to cases where **the entire dimension is clearly a range**, as above.
