### ISSUE TITLE
FillValue not working automatically 

### ISSUE THREAD

**Issue by joanantichna** [Alexander-Barth/NCDatasets.jl#107]
Hello, I'm very new to Julia, but have a bit of experience in Python, and extremely new to GitHub, so sorry in advance if i'm just not placing my comment in the aproppiate place. I'm trying to use the __FillValue_ functionality as to fill the _missing_value_ of a given NETCDF  file pretty much in the same way @Datseris was operating ( Edit: i mentioned him because this message was first intended to be a coment in an already closed issue regarding the same topic and with the same name.. If i knew how to reference it directly i would), but it is not working for me so far.
The context is the following:
I have a set of NETCDF files. Each file has many variables and each variable has the same attributes. For simplification i will explain the problem onto just one, randomly taken, variable called "u", refering to some velocity component. This variable has 3 attributes defined, one of them being "missing_value". What i am trying to do is to add a new attribute that would fill the missing values with the word "missing" as i've seen is the only way to correctly handel such data type to avoid spreading errors. 

The way i do it, i belive, is simple:

```Julia
using NCDatasets
for filename in glob("*.nc","path_to_directory_of_files")      
  ds = NCDataset(filename, "a")
  u_data=ds["u"] 
  u_data.attrib["_FillValue"]="missing"
  break # As to only apply it to the first file ( when it works i will delet this break )
 end 
```

Nevertheless, even if this Attribute-adding is well done, as i can see by just calling the 

"_print(u_data.attrib)_" and observing that the __FillValue_ feature is there now, the missing values, which have been defined as a Number value=-1.0e30 are not converted to the "_missing_" type. Even if redefining the __FillValue_ to another value it's still not working. 

Do you know what could be happening? I've tried many different ways of typing "missing" , as well as numerical values like integrers or floats, so as to avoid it being a typo but none have worked so far.

Pd: As said before, i'm new to git-hub, but also to programing in general and this is the first time i use it to ask something so if there is information needed that is not here i can be more explicit.
Thanks in advance

**Comment by Alexander-Barth** [comment]
Welcome to the community!

I think there is a confusion between the string "missing" and the type missing (without quotes).

In any, case `u_data.attrib["_FillValue"]` should be a value of the same type as the variable `u`. If `u` is a double (or Float64 for julia) and if `-1.0e30` is the value representing missing data, you should rather use 

```julia
 u_data.attrib["_FillValue"] = -1.0e30
```

Do not forget to close the netCDF file with `close(ds)`. It might be useful for you to have a look at  the documentation.

**Comment by joanantichna** [comment]
Thanks for the kind welcoming! And for this really fast answer, i wasn't expecting it.

Although it is true i had that misunderstanding about the string "missing" and the type missing, and also i didn't close the NetCDF file properly, what i really think is the problem now that i look onto your solution is knowing what exactly do the _FillValue and the missing_value attributes do.

If the _FillValue, has to be set as the same one representing the missing_value so as to fill those entries which are represented by the , in my working case, -1.0e30 value with the type missing automatically ( this i what i think was your answer in some way ), then what does the missing_value attribute does? Should i see it as a pre-processing where before that -1.0e30 there were NaN, missings( not in type but in real experimental gaps) and some more kinds of data and after the placement of the attribute all of those are converted to the missing_value number or value (-1.0e30)? But then, why not doing it all at one and defining them as missing type at the beggining instead of goind all the way around first to the missing and then to the _FillV attribute to get the missing well treated?. If that is not what it does, which i can think of to  be the case, could you please give me a hint on what i'm missing?

 

In some way this has led me to more questions i would like to as you if possible( i'm sorry to make it a long coment, in the beggining it's all questions)  because i've read more or less the documentation and i haven't found a solution.
1) Can this missing type conversion of entries be made as to follow a certain relation ( like bigger than or lower than ) and not just a certain equality? To put an example, i'm working with experimental data and some data is missing, but some other have been wrongly obtained and as a result the value differs, by a lot, to that expected or that already known to be. So i would like to have a missing type in those entries to ( the kind of functionality python has with the Numpy Masked Array library.

2) Is there a way to delete attributes? I was working with an already given NECTDF file and so when having to add the _FillValue attribute i also added some self-made attribute example as to see how were to be done but now i can't delete it and can't find in the documentation any command to do it.

3) This one is more personal.  I'm encontering a surprising behavior when running the following code: ( pretty much an upgraded version of the former  i send to start the issue)
```Julia
using NCDatasets
using Glob
for filename in glob("*.nc","/pathtofile")
    ds = NCDataset(filename, "a")
    u_a=ds["u"]
    u_a.attrib["_FillValue"]=-1.0e30
    print(u_a[:])
    close(ds)
    break
end
```
The first time i run it, in Jupyter Notebook, even if the _FillValue attribute is changed correctly, as i can see using the print functionality, the program doesn't do the conversion to missing. Instead is in the second run that this is applied, while the _FillValue doesn't change.  This has blown my mind so far this morning, as i belive computers are still deterministic and so the same code can't have different outputs :), but i've been trying it all over again and don't know what could be happening. I belive it is dangerous to let it go because when i'm going to have to loop to all files i'm not going to be able to check if it the conversion has been done for all variables and all files at the first try. But i don't know if this can be some issue regarding more Jupyter Notebook than your library...

As i see in the documentation to write a good issue, ( i know this is extremely long issue and i'm sorry for it, i guess time will make me learn to summarize better ) i will put the result of:
```Julia
versioninfo()
using Pkg
Pkg.installed()["NCDatasets"]
```
Which is :
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 
  WORD_SIZE: 
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Pkg.jl:531

v"0.10.4"

And for the test: 
NetCDF library: /usr/lib/x86_64-linux-gnu/libnetcdf.so.11
NetCDF version: 4.4.1.1 of Sep  8 2017 07:26:52 $
Test Summary: | Pass  Total
NCDatasets    |  654    654
Test Summary:  | Pass  Total
NetCDF4 groups |    8      8
Test Summary:          | Pass  Total
Variable-length arrays |   22     22
Test Summary:      |   Pass   Total
Time and calendars | 874621  874621
Test Summary:       | Pass  Total
Multi-file datasets |   45     45
Test Summary:     | Pass  Total
Deferred datasets |   13     13

    Testing NCDatasets tests passed 
Thanks in advance for taking your time with my problems

**Comment by Alexander-Barth** [comment]
Note that only the attribute `_FillValue` is used to determine which value should be flagged as missing. 
This behavior is similar to ncread in matlab (https://www.mathworks.com/help/matlab/ref/ncread.html).
All transformation are documented here https://alexander-barth.github.io/NCDatasets.jl/stable/dataset/#Base.getindex-Tuple{NCDataset,AbstractString}

 The value of the attribute `missing_value` is not used. It is not clear to me why the CF standard defines both.

Q1: Not in NCDataset; but you can make this change once your loaded the data in julia.
Q2: This is currently not possible in NCDatasets. I use the command line tool nco for this. 
Q3: To ensure type stability in Julia, I had to assume that the _FillValue attributes does not change and is not defined after creation of the variable object. I this can lead to surprising results that you are seeing. Does it work when you recreate the variable `u_a` ?

```julia
using NCDatasets
using Glob
for filename in glob("*.nc","/pathtofile")
    ds = NCDataset(filename, "a")
    u_a=ds["u"] # u_a doen't know about the fill value and the presence of the fill value is encoded in the type
    u_a.attrib["_FillValue"]=-1.0e30  # defines the fill value in the NetCDF file, but the type of u_a cannot be changed
    u_a=ds["u"] # reload all relevant attributes
    print(u_a[:])
    close(ds)
    break
end
```

**Comment by joanantichna** [comment]
Alrighty! 
To the Q3 answer: yes, it works now!
Thank you!

**Comment by ctroupin** [comment]
Q2: an example on how to delete an attribute. As @Alexander-Barth said, `nco` is the perfect tool to do this kind of manipulations:

```bash
ncatted -a long_name,lat,d,, gebco_30sec_16.nc

**Comment by ctroupin** [comment]
`
