### ISSUE TITLE
Bounds variable conversion

### ISSUE THREAD

**Issue by rafaqz** [Alexander-Barth/NCDatasets.jl#117]
I'm wrapping bounds variables for GeoData.jl. Currently dimension variables are loaded and converted based on their metadata, e.g. to `DateTime`.

What's the cleanest way to do this for the dimensions bounds matrix - applying CF standards and converting the values to the same type as the dim vector?

Can I just construct a CF variable for the bounds variable using the attrib from the dimension variable? Does that make sense to do?

**Comment by Alexander-Barth** [comment]
By reading to the [docs](http://cfconventions.org/cf-conventions/cf-conventions.html#cell-boundaries), it seems that the bound variable "inherits" the unit and calendar attribute (if present) from the appropriate coordinate variable, but not other relevant attributes (like scale_factor, add_offset or _FillValue). 

For example:
```
dimensions:
  time = UNLIMITED; // (5 currently)
  station = 10;
  nv = 2;
variables:
  float pressure(time,station);
    pressure:long_name = "pressure";
    pressure:units = "kPa";
    pressure:cell_methods = "time: point";
  float maxtemp(time,station);
    maxtemp:long_name = "temperature";
    maxtemp:units = "K";
    maxtemp:cell_methods = "time: maximum";
  float ppn(time,station);
    ppn:long_name = "depth of water-equivalent precipitation";
    ppn:units = "mm";
    ppn:cell_methods = "time: sum";
  double time(time);
    time:long_name = "time";
    time:units = "h since 1998-4-19 6:0:0";
    time:scale_factor = 1.23;
    time:bounds = "time_bnds";
  double time_bnds(time,nv);
```

time_bnds would need to use  time:units but not  time:scale_factor.

Do you interpret the CF document in the same way?

**Comment by rafaqz** [comment]
That seems right. So if I understand, a bounds CFVariable should be constructed with the units and calendar from the attributes of the connected dimension merged into its attributes.

**Comment by Alexander-Barth** [comment]
I added the function `bounds` which allows you to access this variable:

```julia
ncbounds = bounds(ds["time"])
```
Example:
https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/test/test_bounds.jl#L25

Note: the variable `ds["time_bnds"]` is just a regular `CFVariable`, unrelated to the variable `time`.

**Comment by rafaqz** [comment]
Thanks, I'll try that.

> Note: the variable ds["time_bnds"] is just a regular CFVariable, unrelated to the variable time.

I don't quite understand this statement, given the line: ` time:bounds = "time_bnds";`

**Comment by Alexander-Barth** [comment]
Sorry if I was not clear.
In my initial implementation `ds["time_bnds"][1]` would return a Float64. Only `bounds(ds["time"])[1]` would return a DateTime (using the example above). But after thinking again about this issue, `ds["time_bnds"][1]` should also return a `DateTime`. The current version of the master has this new behaviour.

**Comment by rafaqz** [comment]
That sounds better actually! Probably my current implementation will just work now. Thanks.

**Comment by Alexander-Barth** [comment]
OK, I will close the issue. Feel free to re-open if the issue persists.

**Comment by rafaqz** [comment]
Sorry I forgot to follow up. Its all working, and Im hoping to get bounds vector handling in GeoData soon. Thanks for the help
