### ISSUE TITLE
Allow `*` syntax for multi file loading

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#127]
Python's `xarray` has a nice feature when loading multifile datasets. You can do:

```julia
ERA5_files = "ERA5_monthly3D_reanalysis_*.nc"
xa = xr.open_mfdataset(ERA5_files)
```
and will match all files with the `*` getting all possible values the files have in the directory.

Would be nice if this happened here as well when input string contained the `*` character. 

Would this be accepted as a PR? 

Any tips on how to do this, e.g. using Regex?

**Comment by visr** [comment]
Are you familiar with https://github.com/vtjnash/Glob.jl? This should work:

```julia
using NCDatasets, Glob

ds = NCDataset(glob("ERA5_monthly3D_reanalysis_*.nc"))
```
