### ISSUE TITLE
how to save coordinates

### ISSUE THREAD

**Issue by francispoulin** [Alexander-Barth/NCDatasets.jl#129]
**Describe the bug**

This is not a bug as much as me not understanding the library very well.  Sorry. 

I am trying to save the entries of the coordinates using `defVar` and I get an error when I only pick one variable.

**To Reproduce**
I changed the line in the example to create a file to the following:
```
julia> v_slice = defVar(ds,"temperature_slice",Float32,("lon"))
```

**Expected behavior**

I thought that I could define a one-dimensional field but maybe I can't.  I'm okay if I can't but would like to know how to save the coordinates to a file.  sorry that I couldn't figure this out.

**Environment**

 - operating system: [e.g. Ubuntu 20.04]
 - Julia version:1.6
 - NCDatasets version: v0.11.3
 
**Full output**

This is the error that I obtained.
```
ERROR: MethodError: Cannot `convert` an object of type Char to an object of type Cstring
Closest candidates are:
  convert(::Type{Cstring}, ::Union{Ptr{Int8}, Ptr{Nothing}, Ptr{UInt8}}) at c.jl:167
  convert(::Type{T}, ::T) where T at essentials.jl:205
Stacktrace:
 [1] cconvert(T::Type, x::Char)
   @ Base ./essentials.jl:396
 [2] nc_inq_dimid(ncid::Int32, name::Char)
   @ NCDatasets ~/.julia/packages/NCDatasets/eDnxY/src/netcdf_c.jl:1144
 [3] defVar(ds::NCDataset{Nothing}, name::String, vtype::DataType, dimnames::String; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ NCDatasets ~/.julia/packages/NCDatasets/eDnxY/src/cfvariable.jl:113
 [4] defVar(ds::NCDataset{Nothing}, name::String, vtype::DataType, dimnames::String)
   @ NCDatasets ~/.julia/packages/NCDatasets/eDnxY/src/cfvariable.jl:110
 [5] top-level scope
   @ REPL[128]:1
```

**Comment by visr** [comment]
Ah I think I understand the problem.

> The parameter `dimnames` is a tuple with the names of the dimension.  For scalar this parameter is the empty tuple `()`.

In your line you pass `("lon")` as entry for dimnames. This is equal to `"lon"`. If you want a size 1 tuple, there needs to be a trailing comma, like `("lon",)`.

Now instead of iterating over the tuple elements to give strings that refer to dimensions, it iterates over the string to give characters.

**Comment by francispoulin** [comment]
Thank you @visr , that is exactly what I was missing.  I am still new to Julia and clearly need to learn my syntax much better.  Thank you for the lesson, it is appreciated.
