### ISSUE TITLE
Strings are inconsistent in v0.0.11

### ISSUE THREAD

**Issue by Balinus** [Alexander-Barth/NCDatasets.jl#13]
I do not have access to much info right now (away from "production" computer, but I'm getting some results from Travis CI) but since v0.0.11, some strings are not consistent. For example, units for temperature returns "K\0" instead of "K" for Kelvin units. Other strings seems to be affected. I could provide more info Monday if need be.

Cheers!

**Comment by Alexander-Barth** [comment]
You are right, I noticed this issues when dealing with #12. It should be fixed in the current master branxh

**Comment by Balinus** [comment]
Great! I can confirm that tests are passing with latest master. Thanks!
