### ISSUE TITLE
controlling chunk cache

### ISSUE THREAD

**Issue by johnomotani** [Alexander-Barth/NCDatasets.jl#130]
Hi, sorry if this is the wrong place to post this question, I'm pretty new to Julia and couldn't immediately see any way on discoures.julialang.org or stackoverflow to tag NCDatasets.jl...

Is there any way to call netCDF's `set_chunk_cache()` function? https://unidata.github.io/netcdf4-python/#set_chunk_cache

I'm thinking about making a Julia version of some Python code we have, and we have found that when operating on very large data sets, the netCDF library's default caching behaviour can cause the supercomputer node to run out of memory (~100s of GB), while if we call `set_chunk_cache(0)` (the Python `netCDF4` package provides a wrapper for the C function) to disable the caching, memory usage stays down at a few GB. This happens even if we carefully delete and garbage-collect all the Python variables. The alternative workaround would be to close and re-open the files, but at least in Python this is very slow because we have many (~1000s) of files - maybe it's quicker in Julia but I guess still slow because the opening has to load metadata from disk.

**Comment by Alexander-Barth** [comment]
I just wrapped the C function in `NCDatasets.set_chunk_cache` / `NCDatasets.get_chunk_cache`. Can you check the master version?
(It is surprising to hear that netcdf will build up 100 GB of in-memory cache; I it hope that I will remember your comment when i run myself into this issue :-) )  

Here is an example how to use these functions:
https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/test/test_chunk_cache.jl

**Comment by johnomotani** [comment]
Thanks @Alexander-Barth! I can confirm that we have the same issue with a Julia/NCDatasets version of the script as the Python one I described above. Without calling `set_chunk_cache(size=0)`, the memory used (as reported by ``memstr = read(`pmap $(getpid())`, String); println("memory usage ", parse(Int, split(memstr)[end][begin:end-1]) / 1024^2, " GiB")``) jumps by 5-10GiB every time we read a large array, reaching 120GiB. With that call (which is now possible :smiley:), memory usage fluctuates around 12GiB.

**Comment by johnomotani** [comment]
Fixed by 5cb91db7e2926274e5e408d93d6fa352485c094a.
