### ISSUE TITLE
Wrong output example for ds.attrib in index.md

### ISSUE THREAD

**Issue by petershintech** [Alexander-Barth/NCDatasets.jl#134]
In `index.md`, an output example given for `ds.attrib` shows actually the entire netcdf file structure, rather than only the file's attributes. Here is the part.
```
while to get the global attributes you can do:
```julia
ds.attrib
```
which produces a listing like:

```
NCDataset: file.nc
Group: /

Dimensions
   time = 115

Variables
  time   (115)
    Datatype:    Float64
    Dimensions:  time
    Attributes:
     calendar             = gregorian
     standard_name        = time
     units                = days since 1950-01-01 00:00:00
[...]
```

**Comment by Alexander-Barth** [comment]
Thank you for reporting. I guess the order of the code examples was a bit off. This is now correct in the master branch.
