### ISSUE TITLE
`getindex(::NCDataset, ::String)` scales poorly with # of variables for unlimited data dimension

### ISSUE THREAD

**Issue by charleskawczynski** [Alexander-Barth/NCDatasets.jl#135]
**Describe the bug**

I found that `getindex(::, ::String)` seems to scale poorly with respect to the number of variables for datasets with an unlimited dimension.

**To Reproduce**

```julia
using BenchmarkTools
import NCDatasets

# generate a NetCDF file
function create_dataset(filename)
    NCDatasets.Dataset(filename, "c") do ds

        unlimgrp = NCDatasets.defGroup(ds, "unlimdata")
        NCDatasets.defDim(unlimgrp, "x", 100)
        NCDatasets.defDim(unlimgrp, "t", Inf)

        x = collect(1:100)
        NCDatasets.defVar(unlimgrp, "x", x, ("x",))
        NCDatasets.defVar(unlimgrp, "t", Float64, ("t",))

        limgrp = NCDatasets.defGroup(ds, "limdata")
        NCDatasets.defDim(limgrp, "x", 100)
        NCDatasets.defDim(limgrp, "t", 100)

        x = collect(1:100)
        t = collect(1:100)
        NCDatasets.defVar(limgrp, "x", x, ("x",))
        NCDatasets.defVar(limgrp, "t", t, ("t",))
    end
end

# Add N profiles
function add_n_vars(filename, n)
    var_names = [basename(tempname()) for i in 1:n]
    NCDatasets.Dataset(filename, "a") do ds
        for i in 1:n
            grp = ds.group["unlimdata"]
            NCDatasets.defVar(grp, var_names[i], Float64, ("t", "x"))
            grp = ds.group["limdata"]
            NCDatasets.defVar(grp, var_names[i], Float64, ("t", "x"))
        end
    end
    return var_names
end

get_var(group, var_name) = group[var_name]

function benchmark_get_var(n)
    filename = tempname()
    create_dataset(filename)
    var_names = add_n_vars(filename, n)
    local btlim
    local btunlim
    NCDatasets.Dataset(filename, "r") do ds
        grp = ds.group["limdata"]
        btlim = @belapsed get_var($grp, $(var_names[end]))
        grp = ds.group["unlimdata"]
        btunlim = @belapsed get_var($grp, $(var_names[end]))
    end
    rm(filename)
    return btlim, btunlim
end

N = [
    2,
    2^2,
    2^3,
    2^4,
    2^5,
    2^6,
    2^7,
];

data = map(benchmark_get_var, N)
lim_data = first.(data)
unlim_data = last.(data)

using Plots
plot(N, lim_data .* 10^6; label="limited dim")
plot!(N, unlim_data .* 10^6; label="unlimited dim")
xlabel!("number of variables")
ylabel!("@btime (μs)")
savefig("ncperf.png")
```

**Expected behavior**

I would expect that the performance is similar to the limited data (no data is being loaded). Here's a plot of the above benchmark:

![ncperf](https://user-images.githubusercontent.com/1880641/125351264-bf1afc80-e314-11eb-9396-3230f81b18f2.png)

**Environment**

 - operating system: MacOS Mojave 10.14.6 
 - Julia version: 1.6.0
 - NCDatasets version: NCDatasets v0.11.6
 
**Full output**

No errors.

**Comment by charleskawczynski** [comment]
I profiled this file and saw that [_boundsParentVar](https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/src/cfvariable.jl#L252-L263) (which is called in [getindex(::Dataset, ::SymbolOrString)](https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/src/cfvariable.jl#L336)) loops through all of the keys to return the variable name iff the bounds attribute matches the variable name.

**Comment by charleskawczynski** [comment]
I can confirm that changing [this line](https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/src/cfvariable.jl#L345) to `parentname = nothing`, the same benchmark gives

![ncperf](https://user-images.githubusercontent.com/1880641/125496508-4d0a677a-1269-4dfe-99d0-5e135ba6ef73.png)

So, the problem seems to be with `_boundsParentVar`.

**Comment by Alexander-Barth** [comment]
The problem is that in the CF conventions, two variables can be linked via the `bounds` attribute (https://github.com/Alexander-Barth/NCDatasets.jl/issues/117). So in NCDatasets, we need to iterate thought all variables so detect this mapping.

It appears that for files with unlimited dimensions, the time in the C library increases linearly with the number of variables for reading netcdf attributes. So in combination, this results in a quadratic scaling.

The code paths in NCDatasets is identical for files with limited and unlimited dimensions. I suspect that they are optimization in NetCDF/HDF5 which are only done for files without  unlimited dimensions.

In the tentative patch, I load the mapping via the `bounds` attribute for read-only files once the file is open. The quadratic cost is still there and I do not think that is can be avoided but it only occurs once for read-only files.

For 128 variables, we have a slow-down of about 12 milliseconds. It is noticeable in a larger application, once you start to load data? Or do you have many more variables than 128?

**Comment by charleskawczynski** [comment]
Hi @Alexander-Barth, thanks for looking into this.

> In the tentative patch, I load the mapping via the bounds attribute for read-only files once the file is open. The quadratic cost is still there and I do not think that is can be avoided but it only occurs once for read-only files. For 128 variables, we have a slow-down of about 12 milliseconds. It is noticeable in a larger application, once you start to load data? Or do you have many more variables than 128?

This patch definitely an improvement (my current work-around is creating a dict that calls the expensive function, `getindex`, and stores the result in a dict). However, it does leave us restricted with opening/closing nc file(s) once and writing/appending in-between, rather than allowing use to open-close at each iteration of our solve, which makes capturing the dataset of crashed simulations much more complicated.

In my use-case, we have at least (maybe more) ~115 variables, and `getindex(::NCDataset, ::String)` dominates the cost of the entire simulation-- it increases the runtime from ~1 minute to, IIRC, ~40 minutes (there are many iterations, and therefore many calls to this code path).

This code was translated from python, which doesn't seem to have this issue--I'll try to replicate this benchmark in python and post it later, to be sure. Are you familiar with the implementation in python? Do you know if they follow CF conventions?

Thanks again for looking into this, NCDatasets.jl works really well, and this is the only issue I've run into.

**Comment by Alexander-Barth** [comment]
>  However, it does leave us restricted with opening/closing nc file(s) once and writing/appending in-between, rather than allowing use to open-close at each iteration of our solve, which makes capturing the dataset of crashed simulations much more complicated.

I am wondering, if you are aware of the [sync](https://alexander-barth.github.io/NCDatasets.jl/stable/dataset/#NCDatasets.sync) function wrapping the [nc_sync](https://www.unidata.ucar.edu/software/netcdf/docs/group__datasets.html#gaf2d184214ce7a55b0a50514749221245) function. From the docs:

>      There are two reasons you might want to synchronize after writes:
>            * To minimize data loss in case of abnormal termination, or
>            * To make data available to other processes for reading immediately after it is written. 

If you keep the NetCDF dataset open, you can also reuse the `NetCDF.CFVariables`, e.g.

```julia
output = ds["output"]
for i = 1:10000
   output[:,:,i] = ...
   sync(ds)
end
```
>  ~1 minute to, IIRC, ~40 minutes

That's indeed a lot! If I am not mistaken, the `python-netCDF4` does not automatically convert time variables and it is up to the users to get the correct time units (possibly taking into account the `bounds` attribute).

I would be interested how this is handeld in `xarray` (and if my interpretation for `python-netCDF4` is correct). Strangely, if I open the file generated by [`test_bounds.jl`](https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/test/test_bounds.jl) in xarray I get the error. `cftime` (version 1.1.3) is well installed. I tried xarray version 0.18.2. The CF conventions includes example like  `days since 1979-01-01`, so the units should be good. 

You seem to know python better than I do ;-), maybe I am doing something stupid.

```python
In [2]: import xarray as xr
In [4]: ds = xr.open_dataset("test_bounds.nc")
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/xarray/coding/times.py in decode_cf_datetime(num_dates, units, calendar, use_cftime)
    235         try:
--> 236             dates = _decode_datetime_with_pandas(flat_num_dates, units, calendar)
    237         except (KeyError, OutOfBoundsDatetime, OverflowError):

~/.local/lib/python3.8/site-packages/xarray/coding/times.py in _decode_datetime_with_pandas(flat_num_dates, units, calendar)
    191         warnings.filterwarnings("ignore", "invalid value encountered", RuntimeWarning)
--> 192         pd.to_timedelta(flat_num_dates.min(), delta) + ref_date
    193         pd.to_timedelta(flat_num_dates.max(), delta) + ref_date

~/.local/lib/python3.8/site-packages/pandas/core/tools/timedeltas.py in to_timedelta(arg, unit, errors)
    121     # ...so it must be a scalar value. Return scalar.
--> 122     return _coerce_scalar_to_timedelta_type(arg, unit=unit, errors=errors)
    123 

~/.local/lib/python3.8/site-packages/pandas/core/tools/timedeltas.py in _coerce_scalar_to_timedelta_type(r, unit, errors)
    127     try:
--> 128         result = Timedelta(r, unit)
    129     except ValueError:

pandas/_libs/tslibs/timedeltas.pyx in pandas._libs.tslibs.timedeltas.Timedelta.__new__()

pandas/_libs/tslibs/timedeltas.pyx in pandas._libs.tslibs.timedeltas.convert_to_timedelta64()

pandas/_libs/tslibs/conversion.pyx in pandas._libs.tslibs.conversion.cast_from_unit()

OverflowError: Python int too large to convert to C long

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/xarray/coding/times.py in _decode_cf_datetime_dtype(data, units, calendar, use_cftime)
    148     try:
--> 149         result = decode_cf_datetime(example_value, units, calendar, use_cftime)
    150     except Exception:

~/.local/lib/python3.8/site-packages/xarray/coding/times.py in decode_cf_datetime(num_dates, units, calendar, use_cftime)
    237         except (KeyError, OutOfBoundsDatetime, OverflowError):
--> 238             dates = _decode_datetime_with_cftime(
    239                 flat_num_dates.astype(float), units, calendar

~/.local/lib/python3.8/site-packages/xarray/coding/times.py in _decode_datetime_with_cftime(num_dates, units, calendar)
    169     return np.asarray(
--> 170         cftime.num2date(num_dates, units, calendar, only_use_cftime_datetimes=True)
    171     )

cftime/_cftime.pyx in cftime._cftime.num2date()

cftime/_cftime.pyx in cftime._cftime.utime.num2date()

cftime/_cftime.pyx in cftime._cftime.DateFromJulianDay()

cftime/_cftime.pyx in cftime._cftime.DateFromJulianDay.getdateinfo()

cftime/_cftime.pyx in cftime._cftime._IntJulianDayToDate()

ValueError: julian day must be a positive integer

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-c90265096d63> in <module>
----> 1 ds = xr.open_dataset("test_bounds.nc")

~/.local/lib/python3.8/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)
    494 
    495     overwrite_encoded_chunks = kwargs.pop("overwrite_encoded_chunks", None)
--> 496     backend_ds = backend.open_dataset(
    497         filename_or_obj,
    498         drop_variables=drop_variables,

~/.local/lib/python3.8/site-packages/xarray/backends/netCDF4_.py in open_dataset(self, filename_or_obj, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta, group, mode, format, clobber, diskless, persist, lock, autoclose)
    561         store_entrypoint = StoreBackendEntrypoint()
    562         with close_on_error(store):
--> 563             ds = store_entrypoint.open_dataset(
    564                 store,
    565                 mask_and_scale=mask_and_scale,

~/.local/lib/python3.8/site-packages/xarray/backends/store.py in open_dataset(self, store, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta)
     23         encoding = store.get_encoding()
     24 
---> 25         vars, attrs, coord_names = conventions.decode_cf_variables(
     26             vars,
     27             attrs,

~/.local/lib/python3.8/site-packages/xarray/conventions.py in decode_cf_variables(variables, attributes, concat_characters, mask_and_scale, decode_times, decode_coords, drop_variables, use_cftime, decode_timedelta)
    510             and stackable(v.dims[-1])
    511         )
--> 512         new_vars[k] = decode_cf_variable(
    513             k,
    514             v,

~/.local/lib/python3.8/site-packages/xarray/conventions.py in decode_cf_variable(name, var, concat_characters, mask_and_scale, decode_times, decode_endianness, stack_char_dim, use_cftime, decode_timedelta)
    358         var = times.CFTimedeltaCoder().decode(var, name=name)
    359     if decode_times:
--> 360         var = times.CFDatetimeCoder(use_cftime=use_cftime).decode(var, name=name)
    361 
    362     dimensions, data, attributes, encoding = variables.unpack_for_decoding(var)

~/.local/lib/python3.8/site-packages/xarray/coding/times.py in decode(self, variable, name)
    525             units = pop_to(attrs, encoding, "units")
    526             calendar = pop_to(attrs, encoding, "calendar")
--> 527             dtype = _decode_cf_datetime_dtype(data, units, calendar, self.use_cftime)
    528             transform = partial(
    529                 decode_cf_datetime,

~/.local/lib/python3.8/site-packages/xarray/coding/times.py in _decode_cf_datetime_dtype(data, units, calendar, use_cftime)
    157             "if it is not installed."
    158         )
--> 159         raise ValueError(msg)
    160     else:
    161         dtype = getattr(result, "dtype", np.dtype("object"))

ValueError: unable to decode time units 'days since 2000-01-01' with 'the default calendar'. Try opening your dataset with decode_times=False or installing cftime if it is not installed.
```

**Comment by Alexander-Barth** [comment]
OK, I found that for `xarray` (or `cftime`) the time origin must be before the all encoded dates (the number of days since the time origin must always be positive). `xarray` seem to decode the dates correctly then:

```
ds.variables["time_bounds"]
Out[9]: 
<xarray.Variable (time: 3, nv: 2)>
array([['2000-01-01T12:00:00.000000000', '2000-01-02T12:00:00.000000000'],
       ['2000-01-02T12:00:00.000000000', '2000-01-03T12:00:00.000000000'],
       ['2000-01-03T12:00:00.000000000', '2000-01-04T12:00:00.000000000']],
      dtype='datetime64[ns]')
```

**Comment by charleskawczynski** [comment]
> I am wondering, if you are aware of the sync function wrapping the nc_sync function. From the docs:

I wasn't aware of this, thanks for pointing that out!

Sorry, I still haven't gotten around to writing the python benchmark. With the existing work-around, we can get by enough and so I had to switch to higher priority items.

**Comment by kongdd** [comment]
I faced with the same problem. Any solution?
```julia
## version1
@time data = ds[varname][:]

## version2
ind_time = (Dates.year.(dates) .<= 2016) #|> findall
@time data = ds[varname][:, :, ind_time]
```
The version1 cost about 20s, while the version 2 cost few minutes.
ds[varname]: 283×163×20454 Array{Union{Missing, Float32}, 3}

**Comment by Alexander-Barth** [comment]
@kongdd I belief that this is unrelated to this issue. Have you seen the Performance Tips (https://alexander-barth.github.io/NCDatasets.jl/stable/performance/ ) in the documentation? It tells you which request are fast or slow. You should try to use ranges as indices because they are implemented as such by the NetCDF C api.

**Comment by Alexander-Barth** [comment]
Rerunning the original benchmark on current master, I get this:

![ncperf](https://user-images.githubusercontent.com/9881475/173779391-475f66b0-e9fd-40ea-bc67-3315ab11796d.png)

Previously, in the worst case we had 10 000 µs (n = 120, and unlimited dimensions) which is now down to 125 µs (unlimited and limited dimension scale similarily).

With the new function cfvariable you can disable the bounds variable look-up (ignoring a part of the CF conventions which is indeed rarely used) with:

```julia
get_var(group, var_name) = NCDatasets.cfvariable(group,var_name,_parentname = nothing)
```

With this change, the performance is relatively flat and the time about 3.2 µs in the worst case (but the fluctuations are likely to be noise).

![ncperf2](https://user-images.githubusercontent.com/9881475/173782004-f11981ed-a47b-4a22-908e-6aeadd0a6646.png)

Is there anything left to be addressed before this issue can be closed?
