### ISSUE TITLE
cannot open multi file dataset with deferopen = true

### ISSUE THREAD

**Issue by visr** [Alexander-Barth/NCDatasets.jl#138]
**Describe the bug**

When opening a multi file dataset, the default setting is to use `deferopen = true`, as can be seen [here](https://github.com/Alexander-Barth/NCDatasets.jl/blob/f98c3ad037ed4ea175bbdb98227a867f1ade47ce/src/multifile.jl#L126). However it seems that the tests only test `deferopen = false`, and if I turn it on, I get `MethodError: no method matching iswritable(::DeferDataset)`.

**To Reproduce**

I ran test_multifile.jl until [this line](https://github.com/Alexander-Barth/NCDatasets.jl/blob/f98c3ad037ed4ea175bbdb98227a867f1ade47ce/test/test_multifile.jl#L94), there I set `deferopen = true`.

**Environment**

 - operating system: Windows
 - Julia version: 1.7.0-beta3.0
 - NCDatasets version: master
 
**Full output**

```julia
ERROR: LoadError: MethodError: no method matching iswritable(::DeferDataset)
Closest candidates are:
  iswritable(::NCDataset) at c:\Users\visser_mn\.julia\dev\NCDatasets\src\dataset.jl:159
  iswritable(::NCDatasets.MFDataset) at c:\Users\visser_mn\.julia\dev\NCDatasets\src\multifile.jl:83
Stacktrace:
 [1] iswritable(mfds::NCDatasets.MFDataset{DeferDataset, 1, NCDatasets.DeferAttributes, NCDatasets.DeferDimensions, NCDatasets.DeferGroups})
   @ NCDatasets c:\Users\visser_mn\.julia\dev\NCDatasets\src\multifile.jl:83
 [2] NCDatasets.MFDataset(ds::Vector{DeferDataset}, aggdim::String, attrib::NCDatasets.MFAttributes{NCDatasets.DeferAttributes}, dim::NCDatasets.MFDimensions{NCDatasets.DeferDimensions}, group::NCDatasets.MFGroups{NCDatasets.DeferGroups})
   @ NCDatasets c:\Users\visser_mn\.julia\dev\NCDatasets\src\multifile.jl:89
 [3] NCDataset(fnames::Vector{String}, mode::String; aggdim::Nothing, deferopen::Bool, _aggdimconstant::Bool)
   @ NCDatasets c:\Users\visser_mn\.julia\dev\NCDatasets\src\multifile.jl:164
 [4] top-level scope
   @ c:\Users\visser_mn\.julia\dev\NCDatasets\test\test_multifile.jl:95
in expression starting at c:\Users\visser_mn\.julia\dev\NCDatasets\test\test_multifile.jl:95
```

**Comment by Alexander-Barth** [comment]
Good catch! (inconsistent spelling of iswritable vs iswrit**e**able). Thank you for reporting it. The tests have also been expanded for this case. Let me know if you have still issues with multi-file dataset and `deferopen = true`.

**Comment by visr** [comment]
Ah nice, glad that it was only a typo. Good to have tests for this though, thanks!
