### ISSUE TITLE
Prodlem reading byte variable

### ISSUE THREAD

**Issue by ax1ine** [Alexander-Barth/NCDatasets.jl#139]
**Describe the bug**

I'm trying to read a byte variable (GEBCO TID grid) which apparently doesn't work (see the exception text below).

**To Reproduce**
`ds = Dataset("GEBCO_2021_TID.nc", "r")`
`val = ds["tid"]`

All other variables work just fine. This one has the following structure:
`byte tid(lat, lon) (no compression)`
`		tid:long_name = GEBCO Type Identifier `
`		tid:units = 1` 
`		tid:grid_mapping = crs `
`		tid:sdn_parameter_urn = SDN:P01::GEBCOSRC` 
`		tid:sdn_parameter_name = Source identifer of GEBCO grid cell data `
`		tid:sdn_uom_urn = SDN:P06:UUUU `
`		tid:sdn_uom_name = Dimensionless `
`		tid:flag_values = Dimensionless `

I see the only difference with other variables that this one is 'byte'. Both dimensions (Lat, Lon) are 'double'.

**Environment**

 - operating system: Windows 10
 - Julia version: 1.6.1, official binaries from https://julialang.org/downloads/
 - NCDatasets version: 0.11.6
 
**Full output**

`ERROR: LoadError: MethodError: no method matching occursin(::String, ::Float64)`
`Closest candidates are:`
`  occursin(::Union{AbstractChar, AbstractString}, ::AbstractString) at strings/search.jl:621`
`  occursin(::Any) at strings/search.jl:635`

**Comment by ctroupin** [comment]
Hello, 
not a huge contribution here but I could reproduce the issues with my machine, so we can discard an issue due to the O.S..
```julia
MethodError: no method matching occursin(::String, ::Float64)
Closest candidates are:
  occursin(::Union{AbstractChar, AbstractString}, ::AbstractString) at strings/search.jl:621
  occursin(::Any) at strings/search.jl:632
Stacktrace:
 [1] _calendar_time(attrib::NCDatasets.Attributes{NCDataset{Nothing}}; calendar::Nothing, time_origin::Nothing, time_factor::Nothing)
   @ NCDatasets ~/.julia/packages/NCDatasets/NVRlj/src/cfvariable.jl:285
 [2] getindex(ds::NCDataset{Nothing}, varname::String)
   @ NCDatasets ~/.julia/packages/NCDatasets/NVRlj/src/cfvariable.jl:355
 [3] top-level scope
   @ In[6]:1
 [4] eval
   @ ./boot.jl:360 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1090
```

- Ubuntu Release:	20.04
- Julia 1.6.0-rc1
- [85f8d34a] NCDatasets v0.11.6

**Comment by Alexander-Barth** [comment]
The problem here is that the units is a number (1) and not a string ("1"). This should be easy to fix in NCDatasets.jl. But I am not sure if this was intentional from GEBCO.

Can you test the current master?

**Comment by ctroupin** [comment]
I could test with the master branch and it worked without any issue.
If @ax1ine confirms the issue can be closed.

**Comment by ax1ine** [comment]
I confirm that everything works fine now. Thanks lot @Alexander-Barth and @ctroupin ! I'm closing this issue.
