### ISSUE TITLE
Attributes as NC_STRING vs array of NC_CHAR

### ISSUE THREAD

**Issue by timhultberg** [Alexander-Barth/NCDatasets.jl#140]
When writing string attributes (for example like this)
using NCDatasets

fout = ARGS[1]

d = Dataset(fout,"c")
d.attrib["Conventions"] = "CF-1.6"
d.attrib["disposition_mode"] = "Test"
close(d)

They get written as arrays of NC_CHAR rather than using NC_STRING. While this seems perfectly fine for me, my "customer" insists that NC_STRING should be used. Is there a way to achieve this already or can it be implemented in a future version?

**Comment by Alexander-Barth** [comment]
You could use this:


```julia
d = NCDataset("test.nc","c");
d.attrib["disposition_mode"] = ["Test"]
close(d)
```
Attributes are always represented as 1d vectors in NetCDF.

```
$ ncdump -h test.nc 
netcdf test {

// global attributes:
		string :disposition_mode = "Test" ;
}
```

(Which is equivalent for the internal API:

```julia
d = NCDataset("test.nc","c");
NCDatasets.nc_put_att_string(d.ncid,NCDatasets.NC_GLOBAL,"disposition_mode",["Test"])
close(d)
```
)

**Comment by timhultberg** [comment]
Perfect! Thanks a lot. Indeed this solves my problem.
