### ISSUE TITLE
NetCDF: Not a valid data type or _FillValue type mismatch (NetCDF error code: -45)

### ISSUE THREAD

**Issue by truedichotomy** [Alexander-Barth/NCDatasets.jl#145]
**Describe the bug**

When I tried to load a dataset using NCDatasets via OpenDAP, it gives me the following error:

```
julia> ds = NCDataset(http://gliders.ioos.us/thredds/dodsC/deployments/rutgers/ng657-20211002T0000/ng657-20211002T0000.nc3.nc, "r");
ERROR: NetCDF error: Opening path http://gliders.ioos.us/thredds/dodsC/deployments/rutgers/ng657-20211002T0000/ng657-20211002T0000.nc3.nc: NetCDF: Not a valid data type or _FillValue type mismatch (NetCDF error code: -45)
Stacktrace:
 [1] nc_open(path::String, mode::UInt16)
   @ NCDatasets ~/.julia/packages/NCDatasets/opjna/src/netcdf_c.jl:274
 [2] NCDataset(filename::String, mode::String; format::Symbol, share::Bool, diskless::Bool, persist::Bool, attrib::Vector{Any})
   @ NCDatasets ~/.julia/packages/NCDatasets/opjna/src/dataset.jl:287
 [3] NCDataset(filename::String, mode::String)
   @ NCDatasets ~/.julia/packages/NCDatasets/opjna/src/dataset.jl:257
 [4] top-level scope
   @ REPL[8]:1
```

Directly downloading and then loading the NetCDF data file works as expected.

**Expected behavior**

When working correctly, I expect to receive to use the OpenDAP protocol to access NetCDF hosted remotely without having to download the whole file.

**Environment**

 - operating system: macOS 11.6
 - Julia version: 1.7rc1
 - NCDatasets version: v0.11.7

**Comment by truedichotomy** [comment]
Thanks for the explanation @Alexander-Barth! I now certainly understand the issue better. I wonder if it's possible to do a beta release that uses netCDF 4.8.1 for macOS and Linux users while waiting for the version specific issues on Windows system to be resolved.

**Comment by Alexander-Barth** [comment]
This seems to be relevant:
https://github.com/Unidata/netcdf-c/issues/1299#issuecomment-458312804

This work for me:

```
ncdump -h 'http://gliders.ioos.us/thredds/dodsC/deployments/rutgers/ng657-20211002T0000/ng657-20211002T0000.nc3.nc#fillmismatch'
```
