### ISSUE TITLE
fillvalue() is not defined for MFVariable

### ISSUE THREAD

**Issue by kyllingstad** [Alexander-Barth/NCDatasets.jl#148]
The function `fillvalue()` is defined for `Variable` and `CFVariable`, but not for `MFVariable`. The `_FillValue` attribute does exist for multi-file variables that have a fill value, so the lack of a function for it seems to be an oversight.

**Comment by Alexander-Barth** [comment]
Thank you for letting me know. This is fixed in the master version and a test case is added.
