### ISSUE TITLE
Loading time from netcdf file as unixtime directly and NaN for fillvalue?

### ISSUE THREAD

**Issue by truedichotomy** [Alexander-Barth/NCDatasets.jl#151]
I loaded a netCDF file using the `NetCDF4.Dataset` function through `PyCall`. For the time variable it returned `Array{Float64}` in unixtime and used `NaN` for the fillvalue.

When I load the same file using `NCDatasets`, it returned `Array{Union{Missing, DateTime}}` with `missing` for the fillvalue.

I wonder if there is a way for NCDatasets out to behave like the python netCDF4 function (Float64 & NaN for time)?

Thanks.

**Comment by Alexander-Barth** [comment]
As far as I know, python `NetCDF4.Dataset` loads the time variable in the time units as they are stored which may or may not be the unix epoch.

```python
ds = netCDF4.Dataset("FI35200501010_07160_D01.nc")
time = ds["TIME"][0:4] 
```

If you want to load the data without any transformation is julia, this is possible with `ds["time"].var[:]` but then you would need to convert the FillValue by NaN. Doing such conversion is often just a single line of code, therefore I think it is better to leave if outside of NCDatasets.

**Comment by Alexander-Barth** [comment]
For example, replacing a fill value by NaN:

```julia
arr = [1.,2.,3.,9999.]
replace(arr, 9999. => NaN)
```

or `missing` by NaN:

```julia
arr = [1.,2.,3.,missing]
coalesce.(arr, NaN) 
```

`replace(arr, missing => NaN)` would also work. In NCDataset, there is also the `nomissing` function which is similar to  `coalesce` but it gives in some cases a more concrete type, e.g.

```
julia> nomissing([missing,1.f0,2.f0],NaN)
3-element Vector{Float32}:
 NaN
   1.0
   2.0

julia> coalesce.([missing,1.f0,2.f0],NaN)
3-element Vector{AbstractFloat}:
 NaN
   1.0f0
   2.0f0
```

So if the input array of `nomissing` is `Array{Union{Missing,T},N}` the output type is guaranteed to be `Array{T,N} `. The the fill value is converted to the type T.

**Comment by truedichotomy** [comment]
Thanks @Alexander-Barth for the examples!
