### ISSUE TITLE
Multifile datasets

### ISSUE THREAD

**Issue by Balinus** [Alexander-Barth/NCDatasets.jl#16]
Hello!

Is there a plan for loading a multifile dataset? For instance, climate models outputs are often splitted over multiple files (temporally splitted). Loading the dataset where `Dataset` takes an array of string might be useful. I know that xarray does it with the `open_mfdataset()` method.

I'm also thinking that using Dagger.jl for asynchronous loading would be a killer feature for such multifile datasets.

Cheers!

**Comment by Alexander-Barth** [comment]
I agree completely that this would be a very useful feature. When I was using Octave, I implemented ncCatArray which allows you to do read and write to a multi-file dataset as if it were a big array: 
https://octave.sourceforge.io/ncarray/function/ncCatArray.html

I will have a look what I can do in NCDataset.jl!

**Comment by Balinus** [comment]
Nice! That would be a very nice feature imho. Espcially if you can make it asynchronous.

**Comment by Alexander-Barth** [comment]
What I have in mind is that you load the data only when you sub-index the multi-file objected:
```
ds = ... multi-file data-set... # no loading of data
temperature = ds["temperature][:,:,:,1] # load of the 1st slice
```

Is this what you mean by asynchronous ?

**Comment by Balinus** [comment]
Close but not exactly I think. 

say you have `file_1.nc` and `file_2.nc`. Process on CPU would load (or index it with `Dataset`) the data contained in `file_1.nc`, while another process would load/index `file_2.nc`. Then, when everything are loaded/indexed, they are fetched and merged on a given CPU. 

This means that this could potentially scale very well the I/O bottleneck on datasets divided across multiple files (we have one in-house simulation that has 1800 files for a 150 years climate simulations). 

So, to follow with what you wrote:

```julia
ds_cpu_1 = ... file_1.nc from multi-file data-set... # no loading of data
...
ds_cpu_N = ... file_N.nc from multi-file data-set... # no loading of data

ds = fetch_and_merge(ds_cpu_1, ..., ds_cpu_N)
temperature = ds["temperature"][:,:,:,1] 
```
The approach would need the use of Dagger.jl. I must admit that I do not have experience with such an approach, but I'm willing to try. I know the Python `xarray` package use Dask for multifile loading.

**Comment by Alexander-Barth** [comment]
I am not familiar with Dagger (or Dask), but is Dagger supposed to work on any array implementing the AbstractArray interface?

In my tests I also got this issue:
https://github.com/JuliaParallel/Dagger.jl/issues/96

**Comment by Balinus** [comment]
That is a good question. I'll see what I can find.

**Comment by Balinus** [comment]
Seems that JuliaDB is able to load files using Dagger: https://github.com/JuliaComputing/JuliaDB.jl/blob/79b9d1f47e025829c193e32c525f93056e5bacc8/src/io.jl#L134

**Comment by Alexander-Barth** [comment]
To work-around issue JuliaParallel/Dagger.jl#96 one can also access a variable without the replacement of fill values by missing using `variable(ds,"variable name")`. It seems that, for a single file, Dagger can be used in combination with NCDatasets:

```julia
using NCDatasets, Dagger
ENV["JULIA_DEBUG"] = "NCDatasets"
ds = Dataset("/usr/share/doc/libnetcdff6/examples/F90/pres_temp_4D.nc");
X = Distribute(Blocks(12,6,2,1), variable(ds,"pressure"))
size(X) # returns (12, 6, 2, 2)
collect(sum(X,dims = 4))
```
The debugging messages seem to confirm that the data is loaded one time slice after the other:

``` 
┌ Debug: nc_get_vars: [0, 0, 0, 0],[1, 2, 6, 12],[1, 1, 1, 1]
└ @ NCDatasets ~/.julia/dev/NCDatasets/src/netcdf_c.jl:758
┌ Debug: nc_get_vars: [1, 0, 0, 0],[1, 2, 6, 12],[1, 1, 1, 1]
└ @ NCDatasets ~/.julia/dev/NCDatasets/src/netcdf_c.jl:758
```

These values are start, count, stride (0-based and reversed) passed to the C-API.

So it seems we can "just" implement an `AbstractArray` for a multi-file variable and let Dagger do the partioning. If the Dagger's partition size is equal to the size of a variable in a single file, then the files would be loaded sequentially.

However, the missing value issue in Dagger should be resolved.

**Comment by Alexander-Barth** [comment]
There is a first implementation of multi-file support in master. 

`Dataset` can be given an vector of file names:
https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/src/multifile.jl#L6

The resulting multi-file dataset structure behaves like the single-file one.

It seems that Dagger can work with such a multi-file variable (except for the missing value issue):
```julia
using Dagger, NCDatasets
include("test/test_catarrays.jl") # this creates some small test files
mfds = Dataset(fnames);
X = Distribute(Blocks(2,3,1), variable(mfds,"var"))
collect(sum(X,dims = 3))


# same results as
sum(variable(mfds,"var")[:,:,:],dims = 3)
```

**Comment by Balinus** [comment]
I will test it out asap!

**Comment by Balinus** [comment]
I've played with it and it does seems to work. Nice work! 

I will try to implement it directly in ClimateTools and see how I can use it efficiently. I think I'll have to take another approach to computations though!

**Comment by aramirezreyes** [comment]
I am very interested on this. Will try these features soon!

**Comment by Alexander-Barth** [comment]
A first version of the multifile, is available since version 0.5.1 (https://github.com/Alexander-Barth/NCDatasets.jl/releases/tag/v0.5.1)

In the master version, I multifile support does no longer require to open all files simultaneously.
I just wrote a simple example how to use it, which is available here:

https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/docs/src/index.md#multi-file-support-experimental

If you find an bug, do not hesitate to open a new issue.

**Comment by Balinus** [comment]
I'm wondering about a possible problematic use-case and would like to gather some ideas on the current (and future) implementation of multi-file datasets. 

Say we have a multi-file datasets that cannot be loaded in RAM. Say I want to add a random value to **all elements** in the multi-file datasets, leading to the effective loading of the entire datasets onto the RAM. How this use-case could be handled? I mean, in the end, every single values will need to be fetched in memory to add the random value. I'm wondering is there is a way to define a sink (e.g. netCDF file) where the new data are stored as the data-processing is done?

Here, I specifically have in mind statistical post-processing applications to simulated climate data, where a correction is done to values (where we need the whole timeserie for a given grid point) before any reduction of the information is done (averages, etc...). Sometimes, we do not even perform any reduction steps, as we only want a corrected dataset for future use or for sharing with collaborators.

Thanks!

**Comment by Alexander-Barth** [comment]
If you have , say 100 files with with a variable of the size 50x50x1, you can "concatenate" them along the 3rd dimension to have a variable of the size 50x50x100. To prevent that all variables are loaded at once, you should iterate for the 3rd dimensions:

```julia
big_dataset = Dataset(list_of_files,...)
big_var = big_dataset["variable_name"]
for n = size(big_var,3)
   big_var[:,:,n] = do_some_correction(big_var[:,:,n]) 
end
```

I hope this is clear. I think this is also one would do it for python's netCDF4 package (this is the scope of features that I am targeting).

**Comment by Balinus** [comment]
Thanks! 

But this will, in the end, load the entire 50x50x100 dataset in `big_var` no?

**Comment by Alexander-Barth** [comment]
Just one 50x50x1 slice at the time. The loading is done when you slice `big_var[:,:,n]` (i.e. when the method `getindex` is called). The function `size` retrieved just the metadata (dimension length), not the entire dataset.
At the end of the loop, the whole dataset would have been read and written, but it would not have been in RAM at the same time.

Note for write access, one cannot use the `deferopen` option.

**Comment by Balinus** [comment]
ok, I see. That's very nice! 

My use case would be to load the entire timeserie at one grid-point for a given iteration. I'll write some code and see how it goes. Cheers!

**Comment by Alexander-Barth** [comment]
This should work, but it will be quite slow as you would load one scalar of every file at the time.
If you can, I would load multiple time series at a time, for example:

```julia
for i = size(big_var,1)
   big_var[i,:,:] = do_some_correction(big_var[i,:,:]) 
end
```

**Comment by Balinus** [comment]
Yes, I guess that will be slow indeed (no choice though as the bias correction technique needs the whole timeserie distribution). 

The idea of loading more than 1 grid-points is certainly feasible, at least for most datasets. A counter-example would be Daymet (1km grid, daily values) would not be possible (about 8000x8000 grid points).

Thanks!

**Comment by Balinus** [comment]
Just tried to loop over the time dimensions (3rd one) and indeed, this is very slow, even for single-file datasets (which wasn't small though). Process is like using about 5-10% of my CPU. hehe! 

I'll have to think about a method where I can do out-of-core calculations that is at least half as efficient as `xarray` for instance.

**Comment by aramirezreyes** [comment]
I am trying to use this but right now the largest time in my process is the file reading. I am very interested in contributing to help this work faster. 
I would like to know if it is possible to begin with, what is in other packages that make the reading faster and how can we make it happen here?

I am not aware at all on the nature of data I/O but I am willing to help to get something as good as xarray.

**Comment by Alexander-Barth** [comment]
Thanks a lot for your help, Argel!

It would be interesting to run Julia's profiler to check where the time is spent. Would it possible for you to put the code that does netCDF data reading in a function, and then run the profiler on this function?

https://docs.julialang.org/en/v1/manual/profile/index.html#Basic-usage-1

Note "it's a good idea to first run the code you intend to profile at least once (unless you want to profile Julia's JIT-compiler)"  (otherwise the output of `Profile.print()` would be quite cluttered)

Much of the speed of xarray comes from dask (I think, at least for computing). The equivalent of dask in Julia in dagger, where there is an issue in dagger preventing it to work with Missing values (JuliaParallel/Dagger.jl#96). If somebody interested in out-of-core computing capability (similar to xarray) could propose a fix for this issue, it would already be a quite significant step forward.

**Comment by Balinus** [comment]
Just found out about [Dispatcher.jl](https://github.com/invenia/Dispatcher.jl) which seems an alternative to Dagger. I wonder if this can be easier to use than Dagger? I must admit I understand half of the things in scheduler overall...!

**Comment by aramirezreyes** [comment]
If Dispatcher is slightly documented then it is a good alternative to Dagger!
