### ISSUE TITLE
Get variable by `standard_name`

### ISSUE THREAD

**Issue by adigitoleo** [Alexander-Barth/NCDatasets.jl#160]
Because `standard_name` actually has a spec, it could be useful to extract variables/dimensions from CF-compliant file based on the standard_name. For example, there is `longitude` and `latitude` for the common case of geographical dimensions, however while trying to write a function that can consume a variety of .nc files I found that the `varname` did not always match the `standard_name`. This leads to a situation where I have to check for `lat`/`lon` dimension names as well.

I think the default behaviour should always be reading based on `varname`, but perhaps some additional method to read a variable given its `standard_name` would allow for more reusable code (at least when dealing with CF conventions).

**Comment by adigitoleo** [comment]
[the CF standard name spec](http://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html) for reference

**Comment by visr** [comment]
Is `varbyattrib` what you are looking for? https://alexander-barth.github.io/NCDatasets.jl/latest/#Get-one-or-several-variables-by-specifying-the-value-of-an-attribute

**Comment by adigitoleo** [comment]
Works, thanks! Missed that when reading through somehow.
