### ISSUE TITLE
Windows: Can't load files with unicode characters

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#162]
Hi, I've spent about an hour wonder why I can't do this:
```
julia> file = files[1]
"C:\\Users\\m300808\\Desktop\\ERA5_original\\ERA5_hourly_Ω_2001.nc"

julia> d = NCDataset(file)
ERROR: NetCDF error: Opening path C:\Users\m300808\Desktop\ERA5_original\ERA5_hourly_Ω_2001.nc: No such file or directory (NetCDF error code: 2)
Stacktrace:
 [1] nc_open(path::String, mode::UInt16)
   @ NCDatasets C:\Users\m300808\.julia\packages\NCDatasets\c8XyT\src\netcdf_c.jl:273
 [2] NCDataset(filename::String, mode::String; format::Symbol, share::Bool, diskless::Bool, persist::Bool, attrib::Vector{Any})
   @ NCDatasets C:\Users\m300808\.julia\packages\NCDatasets\c8XyT\src\dataset.jl:187
 [3] NCDataset (repeats 2 times)
   @ C:\Users\m300808\.julia\packages\NCDatasets\c8XyT\src\dataset.jl:157 [inlined]
 [4] top-level scope
   @ REPL[5]:1

julia> isfile(file)
true
```
The file exists. It is an `.nc` file downloaded from ERA5, so it should be totally valid. Is it because the filename has Unicode Characters?

```
 [85f8d34a] NCDatasets v0.11.9
```

**Comment by Datseris** [comment]
......................... renaming the file to just `W.nc` loads it without a problem. Why can't it load files with unicode...? That's really odd.

**Comment by ctroupin** [comment]
I've tried `ncdump` on an existing file with unicode characters, it doesn't work either.
```bash
ncdump: Ω.nc: Ω.nc: No such file or directory
```

**Comment by Datseris** [comment]
The problem is the discussion in the cited issue is simply too complex for my skill level. If you can tell me something actionable I can do to help, I'll try to do it.

**Comment by Alexander-Barth** [comment]
If a windows use could test netcdf-c with the mingw compiler (available e.g. in [MSYS2](https://www.msys2.org/) or cygwin) and report back to  Unidata/netcdf-c any issues when running the commands, that would already be very helpful.

```bash
./configure
make 
make check
```

**Comment by Alexander-Barth** [comment]
Interestingly, NCDatasets on Linux can handle such files:

```
julia> using NCDatasets; NCDataset("Ω.nc")
NCDataset: Ω.nc
Group: /
```
So it seems that on Linux, the problem is limited to Ubuntu's `ncdump` (version 4.7.3, NCDatasets uses NetCDF version 4.7.4). We would really need a couple of Windows champions helping with Windows-specific issues here 😀

**Comment by Alexander-Barth** [comment]
See also:
https://github.com/Unidata/netcdf-c/issues/2049
https://github.com/Unidata/netcdf-c/issues/2402

Some additional context:
https://blog.r-project.org/2020/05/02/utf-8-support-on-windows/

**Comment by Alexander-Barth** [comment]
This issue should be handled upstream.
