### ISSUE TITLE
Automatic date detection missing in floating numbers as time

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#169]
So I have an .nc file which has the following time information:

```
Variables
  time   (335)
    Datatype:    Float64
    Dimensions:  time
    Attributes:
     standard_name        = time
     bounds               = time_bnds
     units                = day as %Y%m%d.%f
     calendar             = proleptic_gregorian
     axis                 = T
```
Now, once I load the data I do not get a `DateTime` object:
```
julia> t = NCDataset(FILE_NAME)["time"] |> collect
335-element Vector{Float64}:
 2.0200201489583332e7
 2.0200202489583332e7
 2.0200203489583332e7
 2.0200204489583332e7
 2.0200205489583332e7
...
```
`xarray` successfully provides datetime object for the time dimension on loading the same dataset.

I am not sure what we are missing for this particular format. Link to a (smaller) file with only 1 time entry: https://owncloud.gwdg.de/index.php/s/Z5zvx5DQcMjSIWy 

Version:
```
  [85f8d34a] NCDatasets v0.11.9
```
Windows 10. 

I don't think versions/OS matter for this issue, we may have some incomplete logic in the datetime detection code. Can you please point me where in the source the datetime detection occurs?

**Comment by Datseris** [comment]
The date-to-be-detected is also in the filename's title, for the file I share above it is 2020-02-01, 00:00 h.

**Comment by Alexander-Barth** [comment]
> xarray successfully provides datetime object for the time dimension on loading the same dataset.

Surprisingly, on my system xarray provides only a regular array of floats

```python
import xarray as xr
data = xr.open_dataset("download.nc")["time"].to_numpy()
data
#  array([20200201.48958333])
data.dtype
# dtype('float64')
xr.__version__
#  '2022.3.0'
```
```
In [6]: xr.open_dataset("download.nc")["time"]
Out[6]: 
<xarray.DataArray 'time' (time: 1)>
array([20200201.489583])
Coordinates:
  * time     (time) float64 2.02e+07
Attributes:
    standard_name:  time
    bounds:         time_bnds
    units:          day as %Y%m%d.%f
    calendar:       proleptic_gregorian
    axis:           T
```

**Comment by Datseris** [comment]
So I guess we should close this.
