### ISSUE TITLE
Implement "daysinmonth" and other methods for non-standard calendar

### ISSUE THREAD

**Issue by Balinus** [Alexander-Barth/NCDatasets.jl#17]
Hello!

I think it would be useful to extend some methods for non-standard calendar. For instance, the number of daysinmonth for a 365_day calendar in a leap year should return 28 and not 29. Similarly, for 360_day calendar, each month should return 30.

Here's the implementation in Julia Dates stdlib.
https://github.com/JuliaLang/julia/blob/ab25ae4df2605c1d1c0a8ca7aa503888412594b6/stdlib/Dates/src/types.jl#L146

I'm now heavily leveraging your package in ClimateTools. Thanks again for your hard-work!

edit - Last sentence had a strong typo, I wrote "I'm **not** heavily..."  Oups!

**Comment by Balinus** [comment]
Here's some function I did inside ClimateTools. Does seem to work on my limited test files I had on hand.

```julia
"""
    daysinmonth(D::DateTimeNoLeap)

Workaround to work with non-standard calendar DateTimeNoLeap.
"""
function daysinmonth(D::DateTimeNoLeap)
    DAYSINMONTH2 = (31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
    return DAYSINMONTH2[Dates.month(D)]
end

"""
    daysinmonth(D::DateTimeStandard)

Workaround to work with non-standard calendar DateTimeStandard.
"""
function daysinmonth(D::DateTimeStandard)
    DAYSINMONTH2 = (31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
    return DAYSINMONTH2[Dates.month(D)] + (Dates.month(D) == 2 && isleapyear(Dates.year(D)))
end

"""
    daysinmonth(D::DateTimeProlepticGregorian)

Workaround to work with non-standard calendar DateTimeProlepticGregorian.
"""
function daysinmonth(D::DateTimeProlepticGregorian)
    DAYSINMONTH2 = (31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
    return DAYSINMONTH2[m] + (m == 2 && isleapyear(y))
end

"""
    daysinmonth(D::DateTimeAllLeap)

Workaround to work with non-standard calendar DateTimeAllLeap.
"""
function daysinmonth(D::DateTimeAllLeap)
    DAYSINMONTH2 = (31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
    return DAYSINMONTH2[Dates.month(D)]
end

"""
    daysinmonth(D::DateTime360Day)

Workaround to work with non-standard calendar DateTime360Day.
"""
daysinmonth(D::DateTime360Day) = 30


```

**Comment by Alexander-Barth** [comment]
What do you think about computing the month's length?

```julia
# interface similar to Julia (except for the first parameter)
function daysinmonth(::Type{DT},y,m) where DT <: Union{DateTime, AbstractCFDateTime}
          t = DT(y,m,1);
          return Dates.value((t + Dates.Month(1)) - t) ÷ (24*60*60*1000)
       end

# your interface
function daysinmonth(t::DT) where DT <: Union{DateTime, AbstractCFDateTime}
          return daysinmonth(DT,Dates.year(t),Dates.month(t))
end
```

Clearly, it not as fast as your implementation (especially `daysinmonth(D::DateTime360Day) = 30`), but it also reports the correct month's length for the transition from Julian to Gregorian Calendar:

```
julia> daysinmonth(DateTimeStandard,1582,10)
21
```
21 days is also mentioned here http://www.calwiz.com/calendar.cgi?Function=0.

I think that I can add both interfaces to NCDatasets.

**Comment by Alexander-Barth** [comment]
I love this:

Workaround to work with non-*standard* calendar DateTime*Standard*.

This is what you get when everybody has its own standard :-)

I checked with python's `cftime` to get some reference values for the tests:

```
for T in [cftime.Datetime360Day,cftime.DatetimeAllLeap,cftime.DatetimeGregorian,cftime.DatetimeJulian,cftime.DatetimeNoLeap,cftime.DatetimeProlepticGregorian]:
    print(T,T(1582,11,1) - T(1582,10,1))
   ....:     
<type 'cftime._cftime.Datetime360Day'> 30 days, 0:00:00
<type 'cftime._cftime.DatetimeAllLeap'> 31 days, 0:00:00
<type 'cftime._cftime.DatetimeGregorian'> 21 days, 0:00:00
<type 'cftime._cftime.DatetimeJulian'> 31 days, 0:00:00
<type 'cftime._cftime.DatetimeNoLeap'> 31 days, 0:00:00
<type 'cftime._cftime.DatetimeProlepticGregorian'> 31 days, 0:00:00
```

**Comment by Balinus** [comment]
I think your implementation is certainly cleaner and more general that what I did. More importantly, it returns the right values! :) IMO, both interfaces is needed. 

Indeed, nice catch on the "non-standard calendar DateTimeStandard" ! oups!

**Comment by Alexander-Barth** [comment]
This (and daysinyear) is implemented in commit https://github.com/Alexander-Barth/NCDatasets.jl/commit/b1221f28a3307b937ff065339badd67468fe0b9c .

Thanks for the feedback!

**Comment by Balinus** [comment]
Thanks!
