### ISSUE TITLE
Variable '' not found in file  (NetCDF error code: -49): when loading variable name as string

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#170]
**Describe the bug**

I got a really weird bug after updating to NCDatasets.jl 0.12 from 0.11. Code that was perfectly working is now erroring. The code is super simple:

```
x = NCDataset(CERES)["toa_sw_all_mon"]
```
with error message as in the title and with `CERES` a path to a valid .nc file that I could open last evening. I see nothing about such a breaking change here https://github.com/Alexander-Barth/NCDatasets.jl/releases  (and there is no NEWS/CHANGELOG) file. So, I am not sure. The interface of accessing variables via strings is no longer supported? Or is this a bug?

General feedback: Would be good to know what were the breaking changes when going from 0.11 to 0.12. They should be collected in a changelog or at least stated clearly in the merged PRS with a [BREAKING] tag or so. At least I can't find this information somewhere.

**Comment by kongdd** [comment]
I got the same error with `NCDatasets` v0.12.1 on windows.
```julia
using NCDatasets
x = NCDataset("C:/Users/kongdd/github/jl-spatial/Rasters.jl/test/data/tos_O1_2001-2002.nc")
x["tos"]
```

```julia
ERROR: NetCDF error: Variable '' not found in file C:\Users\kongdd\github\jl-spatial\Rasters.jl\test\data\tos_O1_2001-2002.nc (NetCDF error code: -49)
Stacktrace:
 [1] nc_inq_varid(ncid::Int32, name::String)
   @ NCDatasets C:\Users\kongdd\.julia\packages\NCDatasets\eX5vA\src\netcdf_c.jl:1475
 [2] variable
   @ C:\Users\kongdd\.julia\packages\NCDatasets\eX5vA\src\variable.jl:76 [inlined]
 [3] _getattrib(ds::NCDataset{Nothing}, v::NCDatasets.Variable{Float32, 3, NCDataset{Nothing}}, parentname::String, attribname::String, default::Nothing)
   @ NCDatasets C:\Users\kongdd\.julia\packages\NCDatasets\eX5vA\src\cfvariable.jl:277
 [4] cfvariable(ds::NCDataset{Nothing}, varname::String)
   @ NCDatasets C:\Users\kongdd\.julia\packages\NCDatasets\eX5vA\src\cfvariable.jl:355
 [5] getindex(ds::NCDataset{Nothing}, varname::String)
   @ NCDatasets C:\Users\kongdd\.julia\packages\NCDatasets\eX5vA\src\cfvariable.jl:441
 [6] top-level scope
   @ REPL[17]:1
```
```julia
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

(@v1.7) pkg> st
      Status `C:\Users\kongdd\.julia\environments\v1.7\Project.toml`
  [85f8d34a] NCDatasets v0.12.1
```
Data:
<https://www.unidata.ucar.edu/software/netcdf/examples/tos_O1_2001-2002.nc>

**Comment by Alexander-Barth** [comment]
Thanks a lot for the full reproducer and the stack trace @kongdd. I this makes finding the issue so much easier!

Your reproducer now works on master:

```julia
using NCDatasets
ds = NCDataset("/home/abarth/Downloads/tos_O1_2001-2002.nc")
ds["tos"]
```

output:

```
tos (180 × 170 × 24)
  Datatype:    Float32
  Dimensions:  lon × lat × time
  Attributes:
   standard_name        = sea_surface_temperature
   long_name            = Sea Surface Temperature
   units                = K
   cell_methods         = time: mean (interval: 30 minutes)
   _FillValue           = 1.0e20
   missing_value        = 1.0e20
   original_name        = sosstsst
   original_units       = degC
   history              =  At   16:37:23 on 01/11/2005: CMOR altered the data in the following ways: added 2.73150E+02 to yield output units;  Cyclical dimension was output starting at a different lon;
```

A test case has also been added based on your example:
https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/test/test_bounds.jl#L33

**Comment by Alexander-Barth** [comment]
Please reopen if this does not address your issue fully (I close the issue so that it appears in list of closed issue for the 0.12.2 release)

**Comment by Alexander-Barth** [comment]
For your information this the change which prompted the minor version bump (added now the the release notes of 0.12.0):

> Breaking change: when loading a NetCDF variable all values equal to the `missing_value` attribute are replaced by `missing` following the CF conventions. Previously, only the values equal to `_FillValue` were replaced by `missing`.

**Comment by kongdd** [comment]
Thank u. Works now.
