### ISSUE TITLE
How do I add variables that are located only in a subset of the coordinates?

### ISSUE THREAD

**Issue by tomchor** [Alexander-Barth/NCDatasets.jl#176]
I'd like to create a NetCDF file with some variables that are sliced compared to the whole extent of the dimensions. I realize that's not very clear, so please consider the example below:

```julia
using NCDatasets
data = [Float32(i+j) for i = 1:100, j = 1:110]

ds = NCDataset("/tmp/test.nc","c")

defDim(ds,"lon",100)
defDim(ds,"lat",110)

v = defVar(ds,"temperature",Float32,("lon","lat"))
v[:,:] = data

v_sliced = defVar(ds, "temperature_sliced",Float32,("lon","lat"))
v_sliced[10:20,30:40] = data[10:20,30:40]

close(ds)
```

In the above case the second variable `v_sliced` is redundant (since it's data is contained in `v`), but that won't be the case in my application.

In the case above when I create `v_sliced`, `NCDatasets` reserves a whole 100x110 array for it, but only fills in a 10x10 sub array in the middle with `dara` and the rest of the array gets an arbitrary number. I'd like to have it so that `v_sliced` only has a size of 10x10 but still gets assigned the correct coordinates/labels for its data (without having to create secondary dimensions `lat_sliced` and so on). How can I do that? I couldn't find that in the docs and my attempts have failed.

Thank you!

**Comment by Alexander-Barth** [comment]
You would need to create a new dimension with the appropriate size:

```julia
defDim(ds,"lon11",11)
defDim(ds,"lat11",11)

v_sliced = defVar(ds, "temperature_sliced",Float32,("lon11","lat11"))
v_sliced[:,:] = data[10:20,30:40]
```

or

```julia
# lon11 and lat11 are created automatically
v_sliced = defVar(ds, "temperature_sliced",data[10:20,30:40],("lon11","lat11"))
```

The result:

```
$ ncdump -h /tmp/test.nc
netcdf test {
dimensions:
	lon = 100 ;
	lat = 110 ;
	lon11 = 11 ;
	lat11 = 11 ;
variables:
	float temperature(lat, lon) ;
	float temperature_sliced(lat11, lon11) ;
}
```

The name of the dimension is not important. Typically you would also create the NetCDF variables lon, lat, lon11 and lat11 reflecting that lon11 is a subset of lon (idem for lat).

**Comment by tomchor** [comment]
I see. So basically what I'm getting from this (and some playing around) is that the NetCDF format doesn't allow for two variables of different size to have the same dimensions (with the same name). That's useful information.

Thanks!
