### ISSUE TITLE
Problem reading time

### ISSUE THREAD

**Issue by amarux** [Alexander-Barth/NCDatasets.jl#177]
I think there is an issue with the reading of time variables. Actually, results of NCDatasets differ with those of CFTime `timedecode` function.

I noted an offset leading to a wrong interpretation of the dates. For example, the first date of a file with a calendar type gregorian is 2014-01-01T00:00:00. However, this is interpreted by NCDatasets as 2013-12-31T23:59:10.848. 
I consider this issue could be relevant because if the date (2013-12-31) is required to match with other dataset, it won't lead to correct comparisons.

Maybe this is related to a difference in the output with two calendar types (gregorian vs. standard), but I am not sure at all. 
Using the code below it is possible to reproduce the difference using the example nc file on this link (https://drive.google.com/file/d/1NM-aoXIB-h_uBmBt5m5VR_18XS66Aflk/view?usp=sharing)
```
using CFTime, NCDatasets

ds = NCDataset("test.nc")
time1 = ds["time"][:]

vartime = variable(ds, "time")
tunits = vartime.attrib["units"]
time2 = timedecode(vartime[:], tunits)

time1
time2
```

Details: 
OS: Linux Mint Tara 19
CPU Architecture: Intel x86_64
Julia version: 1.6.3
NCDatasets v0.11.7

The output of Pkg.status(mode=PKGMODE_MANIFEST)  can be found in the attached text file [PkgStatuts.txt](https://github.com/Alexander-Barth/NCDatasets.jl/files/8767049/PkgStatuts.txt)

Thank you for all!

**Comment by Alexander-Barth** [comment]
Maybe you can put it on a google drive (or any other hosting service) and share it with a public link? If it is large it would be good to reduce its size with e.g. [nco](http://nco.sourceforge.net/) or similar tools to include just to first time instance. Please provide all other information from the issue template:

* operating system: [e.g. Ubuntu XX.YY]
* CPU architecture (Intel/AMD x86_64, PowerPC, ARM, Appel M1,...)
* Julia version: [e.g. julia 1.1.1, official binaries from https://julialang.org/downloads/]
* NCDatasets version:
* Output of using Pkg; Pkg.status(mode=PKGMODE_MANIFEST)

Thank you for providing this additional information! It will help a lot and reduce a lot of back and forth questions.

**Comment by amarux** [comment]
Thank you! I edited my message to include the required info!

**Comment by Alexander-Barth** [comment]
Thank you for updating the issue!
The problem is that the time is stored a single precision (oddly the data stored at double precision):

```
	double sla(time, latitude, longitude) ;
		sla:standard_name = "sea_surface_height_above_sea_level" ;
		sla:long_name = "Sea level anomaly" ;
		sla:units = "m" ;
		sla:grid_mapping = "crs" ;
		sla:ancillary_variables = "err_sla" ;
		sla:comment = "The sea level anomaly is the sea surface height above mean sea surface; it is referenced to the [1993, 2012] period; see the product user manual for details" ;
		sla:_ChunkSizes = 1, 50, 50 ;
	float time(time) ;
		time:standard_name = "time" ;
		time:long_name = "Time" ;
		time:units = "days since 1950-01-01 00:00:00" ;
		time:calendar = "standard" ;
``` 

in single precision you can only represent the the dates 2013-12-31T23:59:10.848 and 2014-01-01T00:03:32.992  due to the limited precision:

```
julia> ds["time"].var[1]
23376.0f0

julia> DateTime(1950,1,1) + Dates.Millisecond(round(Int, (23376.f0) * (24*60*60*1000)))
2013-12-31T23:59:10.848

julia> DateTime(1950,1,1) + Dates.Millisecond(round(Int, nextfloat(23376.f0) * (24*60*60*1000)))
2014-01-01T00:03:32.992
```

Essentially your smallest time resolution is 2.8 minutes (if you store the time in single precision):

```
julia> eps(23376.f0) * (24*60)
2.8125f0
```

(For double precision number, the resolution would be 0.3 micro seconds.

```
julia> eps(23376.0) * (24*60*60)
3.14321368932724e-7
```

For this reason I store all coordinates in double precision as the coordinates are generally only relatively small vectors).

But I added a special case to NCDatasets when time variables are stored as single precision they will get promoted internally to double precision. So using the master version, you now get:

```
julia> ds["time"][1]
2014-01-01T00:00:00
```

**Comment by Alexander-Barth** [comment]
Feel free to reopen if the error persists. Thank you for reporting.
