### ISSUE TITLE
yearmonthday function

### ISSUE THREAD

**Issue by Balinus** [Alexander-Barth/NCDatasets.jl#18]
Hello again!

Similar to the [daysinmonth](https://github.com/Alexander-Barth/NCDatasets.jl/issues/17) issue, I think another useful function would be the `yearmonthday`.

To put in context, I'm developing a function that does some daily calculation from sub-daily temporal data (daily means,  sums, etc..). Hence, to construct the output array (daily data), I need to know how many unique days is contained in the input array (sub-hourly data).

For example: 

```julia
using Dates
d = DateTime(2000, 01, 01, 0, 0, 0):Hour(1):DateTime(2000,12, 31)
arraylen = unique(Dates.yearmonthday.(Dates.days.(d)))

dataout = Array{Float64}(undef, N, M, arraylen)
```

But the function is not defined for DateTimeNoLeap, etc...

For reference, the original Julia Dates `yearmonthday` function is here.
https://github.com/JuliaLang/julia/blob/c670f1acdba1971b8545f1c3f3b0cfe55ee0d3f5/stdlib/LibGit2/src/signature.jl#L40

**Comment by Alexander-Barth** [comment]
Hi Philippe, I just implemented these functions:
```
julia> Dates.yearmonthday(NCDatasets.DateTimeStandard(2004,1,1,0,0,0))
(2004, 1, 1)

julia> Dates.yearmonth(NCDatasets.DateTimeStandard(2004,1,1,0,0,0))
(2004, 1)
```

If this is OK, I will make a new release (unless there are some other one-line-functions to implement for the next release)

**Comment by Balinus** [comment]
Nice, thanks Alexander! Really appreciated!

No other functions comes to mind right now.
