### ISSUE TITLE
Feature : monthday query for non-standard calendar

### ISSUE THREAD

**Issue by Balinus** [Alexander-Barth/NCDatasets.jl#19]
Hello again! 

There are two other functions that I thought might be useful: `dayofyear` and `daysinyear`. I'm using it to do some statistical post-processing for climate models against observational datasets and the transfer functions are defined on julian day of the year.

For example, `DateTimeNoLeap`, the range should be comprised between 1:365 for a leap year and not 1:366. 

Here's julia native interface.
https://github.com/JuliaLang/julia/blob/cda41aebb35eb12a806c586ebad57a20f1cab648/stdlib/Dates/src/query.jl#L106
https://github.com/JuliaLang/julia/blob/cda41aebb35eb12a806c586ebad57a20f1cab648/stdlib/Dates/src/query.jl#L309
https://github.com/JuliaLang/julia/blob/cda41aebb35eb12a806c586ebad57a20f1cab648/stdlib/Dates/src/query.jl#L311

There are other query functions listed here, but I think that with `dayofyear` and `dayinyear` (and the others that you implemented!), you're covering most of the useful use-case.
https://docs.julialang.org/en/v1/stdlib/Dates/index.html#Query-Functions-1

Sorry for all my requests! :)

**Comment by Alexander-Barth** [comment]
No problem, but are you maybe interested to make implementation and submit a pull request?
Thanks a lot

**Comment by Balinus** [comment]
Sure! :)

**Comment by Balinus** [comment]
So apparently, `daysinyear` and `dayofyear` already works! 

I will implement `monthday`. The other Dates query functions all seems to work!

**Comment by Alexander-Barth** [comment]
This is great! Thank you for the update!

**Comment by Balinus** [comment]
See https://github.com/Alexander-Barth/NCDatasets.jl/pull/20

**Comment by Alexander-Barth** [comment]
Thanks again for your contribution! I make a new release unless there is some other similar date function to be implemented.

**Comment by Balinus** [comment]
A pleasure :) The actual query functions cover a lot now!

Not sure how hard that would be to implement but I was thinking about the possibility to build ranges. Not sure how much this is useful or not but it's handy when building a quick time vector for a given calendar. I haven't looked at the difficulty of implementing it.

```julia
using Dates, NCDatasets
d = DateTime(2000, 01, 01):Day(1):DateTime(2000, 12, 31) # returns a range
2000-01-01T00:00:00:1 day:2000-12-31T00:00:00

# Similarly for non-standard calendar
d2 = DateTimeNoLeap(2000, 01, 01):Day(1):DateTimeNoLeap(2000, 12, 31)
ERROR: MethodError: no method matching guess(::DateTimeNoLeap, ::DateTimeNoLeap, ::Day)
Closest candidates are:
  guess(::DateTime, ::DateTime, ::Any) at /home/user/Programmes/julia/usr/share/julia/stdlib/v1.0/Dates/src/ranges.jl:9
  guess(::Date, ::Date, ::Any) at /home/user/Programmes/julia/usr/share/julia/stdlib/v1.0/Dates/src/ranges.jl:10
Stacktrace:
 [1] len(::DateTimeNoLeap, ::DateTimeNoLeap, ::Day) at /home/user/Programmes/julia/usr/share/julia/stdlib/v1.0/Dates/src/ranges.jl:14
 [2] steprange_last(::DateTimeNoLeap, ::Day, ::DateTimeNoLeap) at /home/user/Programmes/julia/usr/share/julia/stdlib/v1.0/Dates/src/ranges.jl:42
 [3] Type at ./range.jl:180 [inlined]
 [4] Type at ./range.jl:231 [inlined]
 [5] _colon at ./range.jl:45 [inlined]
 [6] (::Colon)(::DateTimeNoLeap, ::Day, ::DateTimeNoLeap) at ./range.jl:39
 [7] top-level scope at none:0
```

**Comment by Alexander-Barth** [comment]
It seems to work now for your example:

```julia
using NCDatasets
d2 = DateTimeNoLeap(2000, 01, 01):Day(1):DateTimeNoLeap(2000, 12, 31)
# DateTimeNoLeap(2000-01-01T00:00:00):1 day:DateTimeNoLeap(2000-12-31T00:00:00)
d2[[1,2]]
# 2-element Array{DateTimeNoLeap,1}:
# DateTimeNoLeap(2000-01-01T00:00:00)
# DateTimeNoLeap(2000-01-02T00:00:00)

d2[[end-1,end]]
# 2-element Array{DateTimeNoLeap,1}:
# DateTimeNoLeap(2000-12-30T00:00:00)
# DateTimeNoLeap(2000-12-31T00:00:00)
```

**Comment by Balinus** [comment]
Ah, I see! Thanks, this is a useful function to have I think. 

cheers! I'll close the issue, I think that we covered a lot of material here on this issue. Thanks a again!
