### ISSUE TITLE
Reading `time` from multi-file dataset very slow

### ISSUE THREAD

**Issue by verseve** [Alexander-Barth/NCDatasets.jl#194]
Since `NCDataset v0.12.4` reading the `time` variable from a multi-file dataset is very slow.

```
dataset = NCDataset(dynamic_paths, aggdim = "time", deferopen = false)
nctimes = dataset["time"][:]
```

I did test this on Windows, Julia v.1.6.4, for 323 NetCDF files, each ~40Mb (`dynamic_paths`). 

[Diff since v0.12.3](https://github.com/Alexander-Barth/NCDatasets.jl/compare/v0.12.3...v0.12.4) for v0.12.4 notes:
Slice of a multifile variable is now a subtype of `AbstractArray{Union{Missing,T},N} where {T,N}` for compatibility with `nomissing`.
Could this change be causing the slow performance?

**Comment by Alexander-Barth** [comment]
Can you share the timings of `@time dataset["time"][:]` in NCDatasets 0.12.4 vs 0.12.3 and create a reproducer (possibly by adapating [test_multifile.jl ](https://github.com/Alexander-Barth/NCDatasets.jl/blob/fbd73ca8ee1c2ab84eb0b755df6faac75af88552/test/test_multifile.jl) ?

**Comment by Alexander-Barth** [comment]
Thanks a lot, I can reproduce the issue locally.

**Comment by Alexander-Barth** [comment]
As a note to my future self, here is how to find the problematic commit with `git bisec`:

File `test/timeout.sh`

```bash
#!/bin/sh
# based on https://schacon.github.io/git/git-bisect-lk2009.html

$HOME/opt/julia-1.7.3/bin/julia $HOME/.julia/dev/NCDatasets/test/issue_194.jl  &

pid=$!
echo "pid $pid"

# 30 s is the maximum time the script should take
sleep 30

# ... and then see if the process is still there.
if ps -p $pid > /dev/null; then
    echo fail
    # It is still running -- that is bad.
    kill $pid; sleep 1; kill $pid;
    exit 1
else
    echo ok
    # It has already finished (the $pid process was no more),
    # and we are happy.
    exit 0
fi
```

```bash
git bisect start v0.12.4 v0.12.3
git bisect run test/timeout.sh
```

Output
```
0fd714cda29d4c64e07f50b1d0a341c6e300274e is the first bad commit
commit 0fd714cda29d4c64e07f50b1d0a341c6e300274e
Author: Alexander Barth <barth.alexander@gmail.com>
Date:   Wed Apr 27 13:31:21 2022 +0200

    start -> offset

 src/CatArrays.jl | 44 +++++++++++++++++++++-----------------------
 1 file changed, 21 insertions(+), 23 deletions(-)

git diff 0fd714cda29d4c64e07f50b1d0a341c6e300274e..0fd714cda29d4c64e07f50b1d0a341c6e300274e^
```

The problematic commit replaces some arrays by tuples in order to reduce allocations. The compiler seem to hang on a `ntuple(i -> ..., Val(M))`. (where M is 323) .  The above commit seem to solve this issue without sacrifying type stability (as far as I can tell) as the Val seems unnessary here:

```
julia> function foo(v::Array{T,N}) where {T,N}
          ntuple(i -> 1,N)
       end
foo (generic function with 1 method)

julia> @code_warntype foo(zeros(2,2))
MethodInstance for foo(::Matrix{Float64})
  from foo(v::Array{T, N}) where {T, N} in Main at REPL[18]:1
Static Parameters
  T = Float64
  N = 2
Arguments
  #self#::Core.Const(foo)
  v::Matrix{Float64}
Locals
  #27::var"#27#28"
Body::Tuple{Int64, Int64}
1 ─      (#27 = %new(Main.:(var"#27#28")))
│   %2 = #27::Core.Const(var"#27#28"())
│   %3 = Main.ntuple(%2, $(Expr(:static_parameter, 2)))::Core.Const((1, 1))
└──      return %3
```

Can you confirm that the master version also work for you?

**Comment by verseve** [comment]
Many thanks for quick fix! I can confirm that the master version is also working for me.
