### ISSUE TITLE
Values aren't correctly written to disk

### ISSUE THREAD

**Issue by tomchor** [Alexander-Barth/NCDatasets.jl#199]
**Describe the bug**

I have a feeling I'm missing something very obvious, but when writing simple Arrays to a NetCDF, the values actually written appears to be very different from the actual Array values (it's always a very large constant value).

**To Reproduce**

```julia
using NCDatasets

ds = NCDataset("test.nc","c")
defDim(ds,"step",100)

x = defVar(ds,"x",Float32,("step",))
x = [Float32(i) for i = 1:100]

close(ds)
```

**Expected behavior**

A description of what you expected to happen.

**Environment**

 - operating system: Manjaro (up to date)
 - CPU architecture (AMD x86_64)
 - Julia version: julia 1.8.2, official binaries
 - NCDatasets version: 0.12.11
 - Output of `using Pkg; Pkg.status(mode=PKGMODE_MANIFEST)`: https://pastebin.com/qCnJt8kQ
 
**Full output**

Here is what running the above commands produce in the REPL:

```julia
julia> using NCDatasets

julia> ds = NCDataset("test.nc","c")
NCDataset: test.nc
Group: /



julia> defDim(ds,"step",100)

julia> x = defVar(ds,"x",Float32,("step",))
x (100)
  Datatype:    Float32
  Dimensions:  step

julia> x = [Float32(i) for i = 1:100]
100-element Vector{Float32}:
   1.0
   2.0
   3.0
   4.0
   5.0
   6.0
   7.0
   8.0
   9.0
  10.0
  11.0
  12.0
  13.0
  14.0
  15.0
  16.0
  17.0
  18.0
  19.0
  20.0
  21.0
   ⋮
  80.0
  81.0
  82.0
  83.0
  84.0
  85.0
  86.0
  87.0
  88.0
  89.0
  90.0
  91.0
  92.0
  93.0
  94.0
  95.0
  96.0
  97.0
  98.0
  99.0
 100.0

julia> ds["x"][:]
100-element Vector{Float32}:
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 ⋮
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
 9.96921f36
```

**Comment by ctroupin** [comment]
Hello,

I think that after creating the variable with `defVar`, you have assign the value to `x` with `x[:] = [Float32(i) for i = 1:100]`, so the whole code would be

```julia
ds = NCDataset("[test.nc](http://test.nc/)","c")
defDim(ds,"step",100)
x = defVar(ds,"x",Float32,("step",))
x[:] = [Float32(i) for i = 1:100]
close(ds)
```

**Comment by tomchor** [comment]
Ah, a silly mistake indeed. I guess you need those brackets to access the Array, right?

Thanks for the fast reply!

**Comment by ctroupin** [comment]
Yes I think they are needed, maybe there is another way to fill the variable with the values, @Alexander-Barth will tell us, but `x[:]` is the one I use the most.
