### ISSUE TITLE
Add support for `@select(ds, lat ∈ min..max)`

### ISSUE THREAD

**Issue by haakon-e** [Alexander-Barth/NCDatasets.jl#200]
As an alternative / more compact supplement to: [[link](https://alexander-barth.github.io/NCDatasets.jl/stable/experimental/#Data-selection-based-on-values)]
```julia
# substitute a local variable in condition using $
lonr = (30,60) # longitude range
latr = (40,90) # latitude range

v = NCDatasets.@select(v,$lonr[1] <= lon <= $lonr[2] && $latr[1] <= lat <= $latr[2])
```

What do you think about adding support for:
```julia
using IntervalSets
lonr = 30..60 # longitude range
latr = ClosedInterval(40, 90) # latitude range
# ^ equivalent constructors
v = NCDatasets.@select(v, lon ∈ 30..60 && lat ∈ $latr)  # \in [TAB]
```

**Comment by Alexander-Barth** [comment]
Indeed that is a nice syntax. This should now work. Here is the list of operators currently supported (after commit 1332241):
https://github.com/Alexander-Barth/NCDatasets.jl/blob/133224137e0af9df7099e2f87317445fe302e220/src/select.jl#L231

**Comment by haakon-e** [comment]
I think you may have a typo in 
https://github.com/Alexander-Barth/NCDatasets.jl/blob/702ceff0a0422eec8b75863a21fa16e8ba274a4a/test/test_select.jl#L308
and
https://github.com/Alexander-Barth/NCDatasets.jl/blob/702ceff0a0422eec8b75863a21fa16e8ba274a4a/test/test_select.jl#L314

These should instead be:
```julia
v = NCDatasets.@select(ds["SST"], ...)
```

in order to verify that _sub_-selection is done correctly.

**Comment by haakon-e** [comment]
Another neat feature is that `IntervalSets` also defines `±(x, y) = ClosedInterval(x - y, x + y)`
so that this now works:
```julia
julia> v = NCDatasets.@select(ds["SST"], lon ∈ $(45 ± 15) && lat ∈ $(65 ± 25))
SST (31 × 51 × 3)
  Datatype:    Float64
  Dimensions:  lon × lat × time

julia> v == NCDatasets.@select(ds["SST"], lon ∈ $(30..60) && lat ∈ $(40..90))
true
```

However, since you didn't add `IntervalSets.jl` as a dependency to `NCDatasets.jl`, you can't do
```julia
julia> NCDatasets.@select(ds["SST"], lon ∈45 ± 15 && lat ∈ 65 ± 25)
ERROR: UndefVarError: ± not defined
Stacktrace:
[...]
```
On the other hand, keeping it out of `NCDatasets` ensures that it doesn't potentially interfere with 
```julia
julia> NCDatasets.@select(ds["SST"], lon ≈ 45 ± 15 && lat ≈ 65 ± 25)
```

It would be appreciated if you could add an example of this in the docstring (noting that you'd need `IntervalSets` in your local environment -- though the syntax is often re-exported by packages such as `Makie`):
https://github.com/Alexander-Barth/NCDatasets.jl/blob/702ceff0a0422eec8b75863a21fa16e8ba274a4a/src/select.jl#L101-L108

For example:
```julia
[...]
# If you have `IntervalSets.jl` available in your julia environment you can also select based on `ClosedInterval`s.
# Both 30..60 and 65 ± 25 construct `ClosedInterval`s, see their documentation for details.
v = NCDatasets.@select(ds["SST"], lon ∈ $(30..60) && lat ∈ $(65 ± 25))
[...]

**Comment by Alexander-Barth** [comment]
> I think you may have a typo in [...]

You are right, thanks a lot!

For now at least, I prefer not to add a new depency to NCDatasets. I am wondering if we can avoid this eval function call here
https://github.com/Alexander-Barth/NCDatasets.jl/blob/307834abb8641ae8e427cb86cf7b3b7984f7872d/src/select.jl#L248

and still have $ interpolation (e.g. $lonr). Having all the code evaluated in the context of the call site would probably make `NCDatasets.@select(ds["SST"], lon ≈ 45 ± 15)` work without a dependency to IntervalSets.

I am wondering how macros like `@btime function_name($parameter)` work (I am quite new to macro myself)...

For example, this just work:

```
julia> using BenchmarkTools, IntervalSets, Statistics

julia> function_name(x) = mean(x)
function_name (generic function with 1 method)

julia> @btime function_name(1..4)
  1.208 ns (0 allocations: 0 bytes)
2.5
```

**Comment by haakon-e** [comment]
Thanks. To be clear, I was not advocating for adding `IntervalSets.jl` as a dependency; merely pointing out a few features and "limitations", in case anyone comes across this issue in the future 🙂

I have no knowledge of macros myself unfortunately, but it sounds like a great query for the julia slack of discourse.

**Comment by Alexander-Barth** [comment]
For your information, I just asked the question here:
https://discourse.julialang.org/t/is-it-possible-to-avoid-eval-in-this-code/93975

I guess this can be closed now.
