### ISSUE TITLE
[Suggestion] easier creation of time axis

### ISSUE THREAD

**Issue by ryofurue** [Alexander-Barth/NCDatasets.jl#208]
Currently, it's a bit tedious to create a time axis for a new dataset. It would be nice if you could do something like
```julia
tax = DateTime(1990, 1, 1):Dates.Day(1):DateTime(2020,1,1)
NCDataset("newfile.nc"; cfconvention=true) do nc
  defDim(nc, "time", length(tax))
  v = defVar(nc, "time", ("time", ); like = tax) #←Asks to use `tax` to determine attributes
  v[:] = tax
  # ⇒ units = "days since yyyy-mm-dd HH:MM:SS" be automatically set.
  #      axis = "T" be automatically set.
end
```
Here, I expect that the NCDataset library would automatically choose an underlying data type (likely Float64) and an appropriate time origin and other standard and helpful attributes.

**Comment by Alexander-Barth** [comment]
This already works:

```julia
tax = DateTime(1990, 1, 1):Dates.Day(1):DateTime(2020,1,1)
NCDataset("newfile.nc", "c") do ds
  defVar(ds,"time",tax,("time",))
end
```
Essentially you give the data to `defVar` rather than just the type.

```
Dataset: newfile.nc
Group: /

Dimensions
   time = 10958

Variables
  time   (10958)
    Datatype:    DateTime (Float64)
    Dimensions:  time
    Attributes:
     units                = days since 1900-01-01 00:00:00
```

**Comment by ryofurue** [comment]
Wow, that's nice!  Very very nice!

The tutorial gives the impression that you need to define a dimension (`defDim`) before defining the corresponding dimension variable (`defVar`).  That's the case for the original netCDF library.

But, `NCDatasets` library just internally `defDim`s when a non-existent dimension is specified in `defVar`.  Is that right?

So, basically you do a way with `defDim` altogether!
```julia
xax = 0:2:358 # longitudes
tax = DateTime(1990, 1, 1):Dates.Day(1):DateTime(2020,1,1)
myvar = get_var()
NCDataset("newfile.nc", "c") do ds
  defVar(ds,"time",tax,("time",))
  defVar(ds,"lon",xax,("lon",))
  ds["lon"].attrib["units"] = "degrees_east"
  defVar(ds,"myvar", myvar, ("lon", "time"))
end
```

**Comment by Alexander-Barth** [comment]
Yes, this is correct.
I added this to the README.md
https://github.com/Alexander-Barth/NCDatasets.jl/commit/295a7159f4667d2009ee15181f97f2e453a7f7fb

Note that you can also define the attributes with defVar (see the examples):
https://alexander-barth.github.io/NCDatasets.jl/stable/variables/#CommonDataModel.defVar

**Comment by ryofurue** [comment]
With this, `defDim()` is necessary only when you need a dimension without coordinate values.  Perhaps you may want the "ensemble" dimension to be like that.
