### ISSUE TITLE
More constructors for CFDateTime types

### ISSUE THREAD

**Issue by BobPortmann** [Alexander-Barth/NCDatasets.jl#21]
The `DateTime` constructors that use `DateFormat` are not implemented for the `CFDateTime` types. For example,
```
julia> DateTime("19991205", "yyyymmdd")
1999-12-05T00:00:00

julia> DateTimeNoLeap("19991205", "yyyymmdd")
ERROR: MethodError: no method matching Int64(::String)
Closest candidates are:
  Int64(::Union{Bool, Int32, Int64, UInt32, UInt64, UInt8, Int128, Int16, Int8, UInt128, UInt16}) at boot.jl:717
  Int64(::Ptr) at boot.jl:727
  Int64(::Float32) at float.jl:697
  ...
Stacktrace:
 [1] DateTimeNoLeap(::String, ::String, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at /Users/portmann/.julia/packages/NCDatasets/O31tb/src/time.jl:317 (repeats 2 times)
 [2] top-level scope at none:0
 ```
It would be handy to have these.

PS Great job on `NCDatasets`, I find it very useful!

**Comment by Alexander-Barth** [comment]
Thank you for your encouragements! 
You probably know the constructors of the type `DateTimeNoLeap(1999,12,5)`.

Parsing dates can quickly become very complicated; do you have an idea how function in julia's `Dates` module could be used for such parsing (so that one does not have to duplicate all the logic)?

**Comment by Alexander-Barth** [comment]
This should now work in the latest version of the master.
I took the approach from AstroTime:
https://github.com/JuliaAstro/AstroTime.jl/blob/master/src/AstroTime.jl

Can you test if it works for you as well?

**Comment by BobPortmann** [comment]
Yes, that works great. It is unfortunate that the functions in DateTime are not written to separate the parsing from the object creation so the parsing part can be easily reused. But the approach from AstroTime works.

Thanks much!

**Comment by Alexander-Barth** [comment]
Thanks you for your confirmation! I will make a new version soon.
