### ISSUE TITLE
Type piracy on CommonDataModel

### ISSUE THREAD

**Issue by rafaqz** [Alexander-Barth/NCDatasets.jl#219]
This line is type piracy on CommonDataModel.jl:

https://github.com/Alexander-Barth/NCDatasets.jl/blob/66d1e672ad5419ac5af96ce022c5904e678fdd30/src/subvariable.jl#L94

Which causes test failures here: https://github.com/rafaqz/Rasters.jl/actions/runs/5475178088/job/14825206026?pr=416#step:5:802

@tcarion FYI

Should it instead dispatch on `SubVariable` ?

**Comment by Alexander-Barth** [comment]
From you comment:

https://github.com/Alexander-Barth/NCDatasets.jl/pull/221#issuecomment-1656708407

Yes, indeed, it would be better to move SubVariable related view function to `CommonDataModel.jl`.

**Comment by rafaqz** [comment]
That means the `SubView` also needs to move to CommonDataModel...

That may be unnnecessary as DiskArrays already handles views pretty well. 

If you dont want to use that, we could instead use a Union of all the netcdf variable types rather than `AbstractVariable`... I'll change the PR to that as a short term fix for now.

**Comment by rafaqz** [comment]
Loking at it this is a bit of a design problem that CommonDataModel depends on `NCDatasets.SubVariable` for handling `view` on all `AbstractVariable`.

Do you want to instead use DiskArrays.jl `SubDiskArray` or `SubVariable` in CommonDataModel.jl ? Even if we move `SubVariable` to CommonDataModel.jl it will cause dispatch issues with `SubDiskArray` and the PRs to add DiskArrays support.


We need to make a pretty high level design choice here: DiskArrays.jl or no DiskArrays.jl

**Comment by tcarion** [comment]
I actually encountered an issue with the `view` method after making `Variable` implement DiskArray, see [this commit](https://github.com/tcarion/NCDatasets.jl/commit/fce58de527f4f868f6ea0f5a34486f6f4ab4ca0f). So this should be fixed when #205 is merged.

**Comment by Alexander-Barth** [comment]
#205 is merged and the type piracy does no longer exists as `SubVariable` has been moved to `CommonDataModel`.
