### ISSUE TITLE
`nomissing(a, NaN)` fails on views of a

### ISSUE THREAD

**Issue by haakon-e** [Alexander-Barth/NCDatasets.jl#220]
**Describe the bug**

`nomissing(a, NaN)` is a great way to replace `missing` with `NaN` in arbitrary arrays. However, if the function is applied to certain views of `a`, then this fails. More specifically, the fallback which accepts subtypes of `AbstractArray` does nothing to its input:
https://github.com/Alexander-Barth/NCDatasets.jl/blob/cb2e615b73c42fa7d9955cd6745ca2582a2a346a/src/variable.jl#L305-L309

**To Reproduce**

```julia
julia> yy = Array{Union{Missing, Float64}, 2}(missing, (2,1))
2×1 Matrix{Union{Missing, Float64}}:
 missing
 missing

julia> yyy = dropdims(yy; dims = 2)
2-element reshape(::Matrix{Union{Missing, Float64}}, 2) with eltype Union{Missing, Float64}:
 missing
 missing

julia> nomissing(yyy, NaN)
2-element reshape(::Matrix{Union{Missing, Float64}}, 2) with eltype Union{Missing, Float64}:
 missing
 missing
```

**Expected behavior**

This appears to be quite easily fixed if `nomissing` instead accepts `AbstractArray`s:
```julia
julia> function nomissing2(da::AbstractArray{Union{T,Missing},N},value) where {T,N}
           return replace(da, missing => T(value))
       end

julia> nomissing2(yyy, NaN)
2-element Vector{Float64}:
 NaN
 NaN
```

<details><summary>**Environment**</summary>

```julia
(myenv) pkg> st NCDatasets
Status `~/.../Project.toml`
  [85f8d34a] NCDatasets v0.12.17

julia> versioninfo()
Julia Version 1.9.2
Commit e4ee485e909 (2023-07-05 09:39 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 4 on 4 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_IMAGE_THREADS = 1
```

</details>

**Comment by Alexander-Barth** [comment]
Very interesting! I did not see any test failure by making this change. The resulting array is no longer a view (but this is consistent with `replace` and `coalesce.`).

Thanks!
