### ISSUE TITLE
.var[:] always returns a vector

### ISSUE THREAD

**Issue by mwlidar** [Alexander-Barth/NCDatasets.jl#233]
.var[:] in the latest version now always makes a vector, even if the source is a higher dim array. This is a change of behaviour and contradicts the docs. Array() still works as expected.

 - operating system: Windows 10
 - Julia version: 1.9.3
 - NCDatasets version: NCDatasets v0.13.1

**Comment by visr** [comment]
NCDatasets 0.13 is a breaking release, where this behavior was changed intentionally. This is written in the release notes here: https://github.com/Alexander-Barth/NCDatasets.jl/releases/tag/v0.13.0

Which are the docs that you say this contradicts? Perhaps some still need updating.

**Comment by mwlidar** [comment]
vairiable.md on master still says:

```
To load the variable v_cf in memory as numeric data you can convert it into an array (preserving its dimensionality structure) with

Array(v_cf)

The syntax v_cf[:] is equivalent with the above, it doesn't make a Vector (like it does on normal Julia arrays).
```
Anyway this quite beraking for me, als there are over 200 places to review and correct manually. At least my regex skills are not enough to come up with an automated conversion...

**Comment by Alexander-Barth** [comment]
Thanks for pointing out where the documentation needs to updated:
https://github.com/Alexander-Barth/NCDatasets.jl/commit/981729f287381a48381c6431f528a159e4e0b88d

**Comment by lupemba** [comment]
Just a note.
I also experience that scalar variables are returned as an vector now. 
I have `instrument_parameters["fsamp"][:]` which previously returned a float but now returns a vector with one element.

**Comment by Alexander-Barth** [comment]
Scalar variable can also be loaded using `[]`, I clarified that in the docs here:
d22fff6bed5f5af62d0efad746d6cd6757c22142

Also for julia this indexing works for scalars '42[] == 42`.

> I like change for the multi dimensional case.

Thank you for noting that 😀 I typically get mostly negative feedback over-here 😅

**Comment by mwlidar** [comment]
While fixing up my code I noticed that Array(v_cf) is not equivalent to v_cf.var[:] even in the vector case, because Array(v_cf) does Missing and DateTime conversion etc. The equivalent would be Array(v_cf.var). Maybe this could be added in some way to the docs.

**Comment by Alexander-Barth** [comment]
OK I added this here:

https://github.com/Alexander-Barth/NCDatasets.jl/commit/148e08658594d20448b14711b57313410c90629e#diff-048ca2e4745de3ff36dc57555fe64b07a4b761109d9c4caafe45df1f1d8e35ffR45
