### ISSUE TITLE
`CITATION.cff` file

### ISSUE THREAD

**Issue by navidcy** [Alexander-Barth/NCDatasets.jl#234]
It'd be nice if there was a `CITATION.cff` file to suggest how people should cite this repo.

**Comment by Alexander-Barth** [comment]
Thank you for bringing that up. Unfortunately, I do not have a good answer what a citation could be.   Maybe I should try to find some time to write a JOSS paper too :-)

**Comment by ctroupin** [comment]
you can also add this repository on Zenodo, so you get a DOI for each release.

**Comment by milankl** [comment]
@Alexander-Barth sorry, only saw this now, yes, please zenodo for the time being and once the JOSS paper is out I'll let you know! If we're supposed to use another citation in between let me know.

**Comment by Alexander-Barth** [comment]
Thanks @milankl !
I am closing this issue.
A [CITATION.cff](https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/CITATION.cff) has been added.
