### ISSUE TITLE
Allow `CartesianIndex` and `CartesianIndices` with `load!`

### ISSUE THREAD

**Issue by haakon-e** [Alexander-Barth/NCDatasets.jl#250]
**Describe the bug**

Reading a dataset normally, you can index it with `CartesianIndex` and `CartesianIndices`, which is often very useful!

For performance reasons it is sometimes useful to preallocate the output array, and therefore use `load!`. However, it appears this kind of indexing does not work with `load!`.

**To Reproduce**

```julia
# create dataset
ds = NCDataset("/tmp/test.nc","c")
defDim(ds,"lon",100)
defDim(ds,"lat",110)
v = defVar(ds,"temperature",Float32,("lon","lat"))
data = [Float32(i+j) for i = 1:100, j = 1:110];
v[:,:] = data;
close(ds)

# reading
ds = NCDataset("/tmp/test.nc")

# works:
ds["temperature"][CartesianIndices((1:10,10:30))]
ds["temperature"][CartesianIndex(1,1)]

# read in-place
v = zeros(Float32, 10, 21);
NCDatasets.load!(variable(ds, "temperature"), v, 1:10,10:30)  # works
NCDatasets.load!(variable(ds, "temperature"), v, CartesianIndices((1:10,10:30)))  # does not work

vv = [1.0f0]
NCDatasets.load!(variable(ds, "temperature"), vv, 1, 1)  # works
NCDatasets.load!(variable(ds, "temperature"), vv, CartesianIndex(5,5))  # does not work
```

<details> <summary> stack traces </summary>

```julia
julia> NCDatasets.load!(variable(ds, "temperature"), v, CartesianIndices((1:10,10:30))) 
ERROR: MethodError: no method matching load!(::NCDatasets.Variable{Float32, 2, NCDataset{Nothing, Missing}}, ::Matrix{Float32}, ::CartesianIndices{2, Tuple{UnitRange{Int64}, UnitRange{Int64}}})

Closest candidates are:
  load!(::NCDatasets.Variable{T, 2}, ::AbstractArray{T}, ::Colon, ::UnitRange) where T
   @ NCDatasets ~/.julia/packages/NCDatasets/ivzVX/src/variable.jl:148
  load!(::NCDatasets.Variable{T, N}, ::AbstractArray{T}, ::Union{Colon, Integer, StepRange, UnitRange}...) where {T, N}
   @ NCDatasets ~/.julia/packages/NCDatasets/ivzVX/src/variable.jl:140
  load!(::CommonDataModel.MemoryVariable, ::Any, ::Any...)
   @ CommonDataModel ~/.julia/packages/CommonDataModel/GGvMn/src/memory_dataset.jl:57
  ...



julia> NCDatasets.load!(variable(ds, "temperature"), vv, CartesianIndex(5,5))  # does not work
ERROR: MethodError: no method matching load!(::NCDatasets.Variable{Float32, 2, NCDataset{Nothing, Missing}}, ::Vector{Float32}, ::CartesianIndex{2})

Closest candidates are:
  load!(::NCDatasets.Variable{T, 2}, ::AbstractArray{T}, ::Colon, ::UnitRange) where T
   @ NCDatasets ~/.julia/packages/NCDatasets/ivzVX/src/variable.jl:148
  load!(::NCDatasets.Variable{T, N}, ::AbstractArray{T}, ::Union{Colon, Integer, StepRange, UnitRange}...) where {T, N}
   @ NCDatasets ~/.julia/packages/NCDatasets/ivzVX/src/variable.jl:140
  load!(::CommonDataModel.MemoryVariable, ::Any, ::Any...)
   @ CommonDataModel ~/.julia/packages/CommonDataModel/GGvMn/src/memory_dataset.jl:57
  ...
```

</details

**Expected behavior**

Cartesian indexing to work with `load!`

**Environment**

<details> <summary> OS info </summary>

```julia
julia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 4 default, 0 interactive, 2 GC (on 4 virtual cores)
Environment:
  JULIA_NUM_THREADS = auto
  JULIA_EDITOR = code

(examples) pkg> st NCDatasets
Status `~/Documents/examples/Project.toml`
  [85f8d34a] NCDatasets v0.14.2
```

</details

**Comment by haakon-e** [comment]
PS: To get around this, in my internals, I currently do variants of:

```julia
inds = CartesianIndices((1:10,10:30))
NCDatasets.load!(variable(ds, "temperature"), v, inds.indices...)

ind = CartesianIndex(5,5)
NCDatasets.load!(variable(ds, "temperature"), vv, ind.I...)
```

**Comment by haakon-e** [comment]
I feel like a fix should be within reach by adding methods to https://github.com/Alexander-Barth/NCDatasets.jl/blob/ce245f0564f22ccaaffde4ed48150d0682fb47f4/src/variable.jl#L455-L465

of the form
```julia
_normalizeindex(n,ind::CartesianIndex) = ind
_normalizeindex(n,ind::CartesianIndices) = ind
```
This doesn't immediately works, e.g. for `CartesianIndex(1,1)` because then `sz` and `indexes` doesn't have the same length. However, `sz` is currently only used for parsing `:`, so perhaps this could be fixed some other way?

Certainly, the `to_indices` method here expands CartesianIndex correctly:
https://github.com/Alexander-Barth/NCDatasets.jl/blob/ce245f0564f22ccaaffde4ed48150d0682fb47f4/src/variable.jl#L95-L108

**Comment by Alexander-Barth** [comment]
Thanks a lot for your detailed issue report.
Yes, it makes totally sense to support CartesianIndex and CartesianIndices with load!!.
The latest commit 74602657efd2ec4beee26a00dd480a1606ed0af6 seems to solve your test case.

(I am wondering if we need `normalizeindexes` at all and could not just rely on `to_indices` instead.)

**Comment by haakon-e** [comment]
Thanks a lot! This seems to work great.

A small aside: In the future, I'd greatly appreciate if my contributions are explicitly acknowledged in the commit(s) ([see how](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line)) with: `Co-authored-by: Haakon Ludvig Langeland Ervik <45243236+haakon-e@users.noreply.github.com>`. I'll try to remember noting this next time too. 
Thanks again for the quick turnaround!
