### ISSUE TITLE
Any simple way to remove or replace variables in a NCDataset?

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#260]
I have two variables `x, y` in a NCDataset. From them I can produce `z = f(x, y)`. I want to add `z` to the dataset and remove `x,y`. Is there a simple way to achieve this? I would be very happy to know! I can even write a tutorial about this for the docs!

**Comment by Alexander-Barth** [comment]
Sadly, the NetCDF C API does not allow this, e.g.

https://github.com/Unidata/netcdf4-python/issues/940
https://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/1998/msg00052.html

But as you probably know, you can re-create a NetCDF file by excluding the variable that you do not want to keep.
https://alexander-barth.github.io/NCDatasets.jl/stable/dataset/#Base.write

**Comment by ctroupin** [comment]
With [`nco`](https://nco.sourceforge.net/) I think it's pretty simple, in particular with https://nco.sourceforge.net/nco.html#ncap2
