### ISSUE TITLE
NCDatasets is using an outdated version of DiskArrays

### ISSUE THREAD

**Issue by charleskawczynski** [Alexander-Barth/NCDatasets.jl#267]
The latest release is not yet compatible with the latest version of DiskArrays. I'm hoping to see if https://github.com/meggart/DiskArrays.jl/pull/193 resolves https://github.com/meggart/DiskArrays.jl/issues/175, however, I'm currently unable to try it out due to this issue.

**Comment by visr** [comment]
I think the current status is https://github.com/Alexander-Barth/NCDatasets.jl/pull/247#issuecomment-2302521586 which hangs on https://github.com/meggart/DiskArrays.jl/issues/186 being fixed.

**Comment by Balinus** [comment]
I think this is fixed now (?)

**Comment by Alexander-Barth** [comment]
Yes, it is fixed in master.

**Comment by charleskawczynski** [comment]
Fantastic, thank you to all those involved in fixing this!
