### ISSUE TITLE
Add topics/keywords to Github page

### ISSUE THREAD

**Issue by Balinus** [Alexander-Barth/NCDatasets.jl#27]
Might be a good idea to add keywords to the main page. https://pkg.julialang.org uses those keywords to index the packages. As an example, NCDatasets does not show up when typing `netcdf`.

Ref: https://discourse.julialang.org/t/new-pkg-julialang-org/22622

**Comment by Alexander-Barth** [comment]
Excellent idea, thanks! I added these:

netcdf
julia
climate-and-forecast-conventions
oceanography
meteorology
climatology

**Comment by Balinus** [comment]
Sounds good!
