### ISSUE TITLE
Is it possible to get memory mapping in NCDatasets?

### ISSUE THREAD

**Issue by aramirezreyes** [Alexander-Barth/NCDatasets.jl#31]
Hi:

I am wondering about ways of improving performance when reading large, multifile datasets.
I declare I am not an expert on this matter, but...

Is it possible for NCDatasets to use mmap? 
HDF5 does it like [this](https://github.com/JuliaIO/HDF5.jl/blob/master/doc/hdf5.md#memory-mapping):

Sorry if this is a dumb question!

**Comment by Alexander-Barth** [comment]
It is certainly not a dump question, but I am not familiar with mmap.
It seems that the option `NC_DISKLESS` cover such as use case:

https://www.unidata.ucar.edu/software/netcdf/docs_rc/md__Users_wfisher_Desktop_gitprojects_netcdf-c_docs_inmemory.html

**Comment by Balinus** [comment]
Possibly with `mmap` ? 

https://docs.julialang.org/en/v1/stdlib/Mmap/index.html#Mmap.mmap

**Comment by Alexander-Barth** [comment]
@Balinus , thanks for the link, but it is  not clear to me how I could use the Julia function `mmap` given that the NetCDF library is in C. Files are open inside the C code of NetCDF.

I exposed in NCDataset the diskless feature of the NetCDF library. But unfortunatetly it did not result in a sizeable speed improvement in my tests (https://github.com/Alexander-Barth/NCDatasets.jl/blob/f2e387009183cf7ae502dd10a4176198bfdc425a/test/test_diskless.jl).

```julia
include("test/test_diskless.jl")
# sequential access, diskless=false
#  2.156 s (2240025 allocations: 124.51 MiB)
# random access, diskless=false
#  3.922 s (2400029 allocations: 134.28 MiB)
# sequential access, diskless=true
#  2.053 s (2240025 allocations: 124.51 MiB)
# random access, diskless=true
#  3.801 s (2400029 allocations: 134.28 MiB)
```

@aramirezreyes, it would be interesting to compare the speed of NCDatasets when reading your data with the speed of the python library netCDF4 using the MFDataset class (python's netCDF4 and the Julia NCDatasets are quite comparable in scope)

**Comment by aramirezreyes** [comment]
You are probably aware of this but I ran a couple tests using 200 files with  3-d variables and 120 files with 4-d variables.

My workflow in julia is something like:

```
using NCDatasets, BenchmarkTools

path2d = "/global/cscratch1/sd/aramreye/sam3d_experimental/homoRad_Fs_noVe_noEvap_500km/f5e-4_2km_1000km_control/exe.sam/OUT_2D/"
path3d = "/global/cscratch1/sd/aramreye/sam3d_experimental/homoRad_Fs_noVe_noEvap_500km/f5e-4_2km_1000km_control/exe.sam/OUT_3D/"
file2d = filter(x -> occursin(r".*\.nc", x), string.(path2d, readdir(path2d)))[1:200];
file3d = filter(x -> occursin(r".*\.nc", x), string.(path3d, readdir(path3d)))[1:120];

file2d = filter(x -> occursin(r".*\.nc", x), string.(path2d, readdir(path2d)))[1:200];
file3d = filter(x -> occursin(r".*\.nc", x), string.(path3d, readdir(path3d)))[1:120];

function readfiles2d()
    U ::Array{Float32,3} = variable(DS2,"USFC")[:,:,:]
    V ::Array{Float32,3} = variable(DS2,"VSFC")[:,:,:]
    P ::Array{Float32,3} = variable(DS2,"PSFC")[:,:,:]
    PW ::Array{Float32,3} = variable(DS2,"PW")[:,:,:]
    LHF ::Array{Float32,3} = variable(DS2,"LHF")[:,:,:]
    SHF ::Array{Float32,3} = variable(DS2,"SHF")[:,:,:]
end
function readfiles3d()
    variable(DS3,"U")[:,:,:,:]
    variable(DS3,"V")[:,:,:,:]
    variable(DS3,"PP")[:,:,:,:]
    variable(DS3,"TABS")[:,:,:,:]
end

DS2 = Dataset(file2d,deferopen=true,aggdim="time");
@time readfiles2d();
close(DS2)

DS3 = Dataset(file3d,deferopen=true,aggdim="time");
@time readfiles3d();
close(DS3)
```

Which yields:
4.5s for the 2d files
and 45s for the 3d files


In Python I am doing:

f```
rom netCDF4 import MFDataset
import numpy as np
import xarray as xr
from glob import glob

%load_ext memory_profiler

Let's try with 2-D data

mfdataDIR2d = "/global/cscratch1/sd/aramreye/sam3d_experimental/homoRad_Fs_noVe_noEvap_500km/f5e-4_2km_1000km_control/exe.sam/OUT_2D/RCE_Muller_expt8.001_512_0000*.nc"
mfdataDIR3d = "/global/cscratch1/sd/aramreye/sam3d_experimental/homoRad_Fs_noVe_noEvap_500km/f5e-4_2km_1000km_control/exe.sam/OUT_3D/RCE_Muller_expt8.001_512_0000*.nc"

files3d = glob(mfdataDIR3d)
files3d.sort()
files3d = files3d[:120]
files2d = glob(mfdataDIR2d)
files2d.sort()
files2d = files2d[:200]

def readfiles2d():
    f2d.variables["USFC"][:]
    f2d.variables["VSFC"][:]
    f2d.variables["PSFC"][:]
    f2d.variables["PW"][:]
    f2d.variables["LHF"][:]
    f2d.variables["SHF"][:]
def readfiles3d():
    f3d.variables["U"][:]
    f3d.variables["V"][:]
    f3d.variables["PP"][:]
    f3d.variables["TABS"][:]

%%time
f2d = MFDataset(files2d)
readfiles2d()

%%time 
f3d = MFDataset(files3d)
readfiles3d()
```

Which yields 2.48s and 48.1s, respectively.

So the performance of the NetCDF implementations are quite comparable, and in fact the difference is not significant when running several times.

**Comment by Alexander-Barth** [comment]
Thanks a lot, these benchmarks are very interesting!
