### ISSUE TITLE
Asmmetry with Missings and DateTime when loading and saving vars.

### ISSUE THREAD

**Issue by rafaqz** [Alexander-Barth/NCDatasets.jl#38]
It seems that `Dataset` vars arrays are automatically typed `Union{Missing,T}` and nodata values converted to `missing`. But at the same time you can't write an array containing missings in `defVar`.

Maybe `defVars` should handle vars containing `missing` automatically converting them to some standard missing value? Then read and write would have more symmetry, and we could just write a a var we just loaded back to netcdf. Otherwise special-case handling of `Missing` is required in the client code.

Unless I'm missing something.

Load/save of datetime is also not symmetrical. It's only converted on load. It would be great to handle conversion of types both ways.

**Comment by Alexander-Barth** [comment]
I think rather the support for such use case is missing :-)

You can now in `defVar` write arrays like these:
```julia
     defVar(ds,"foo_default_fill_value",[missing,1.,2.],("dim",))
    arr = [DateTime(2000,1,1),DateTime(2000,1,2),DateTime(2000,1,3)]
    defVar(ds,"foo_datetime",arr,("dim",))
    arr = [missing,DateTime(2000,1,2),DateTime(2000,1,3)]
     defVar(ds,"foo_datetime_with_fill_value",arr,("dim",))
```

The NetCDF default fill values  (https://github.com/Unidata/netcdf-c/blob/master/include/netcdf.h#L67) are used if the argument `fillvalue` is not specified. 
In case, I misunderstood your issue, can you provide me an example code of what you think should be possible/desirable?

**Comment by rafaqz** [comment]
That's exactly what I was looking for :) Especially just replacing missing with the standard default value without the caller having to known what it is.

Will the date handling also work with CFTime.jl datetime values?

For some background I'm writing `save` methods for GeoData.jl so it will handle load/save of a bunch of formats, which will also allow conversion between formats, without having to specify anything besides the array to save, the type to save it as and the filename.

**Comment by Alexander-Barth** [comment]
I have added support for this now: https://github.com/Alexander-Barth/NCDatasets.jl/commit/3973c94b899bafde17348fb763706fed3caf6321

Please have a look also to this note: 

```
While reading a NetCDF time variable, the dates are converted using the Julia's `DateTime` (based on the proleptic Gregorian calendar following the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard) when possible. When data is written to a NetCDF file (without specifying the calendar), the dates are saved using the default calendar of the NetCDF CF convention (the mixed Julian/Gregorian calendar, called `"standard"`) when possible. 
```

When you write e.g. a `DateTimeJulian` you will get back a date converted to `DateTime`. 
For fine grain control you can always set the calendar attribute before writing the data.

**Comment by rafaqz** [comment]
My main problem is automating these conversions, not the user choosing them specifically. It would be great if you load a file and save it, and it's basically identical to what you loaded without having to think about it at all.

I don't totally understand what the calendar arg is for when the types already encode the calendar type... But as long as the type `DateTimeJulian` can be passed in as the calendar kwarg through NCDatasets to CFTime I can make it work.  This was the reason for the issue over in CFTime.

**Comment by Alexander-Barth** [comment]
I understand your use-case. But I think most NetCDF files use the default calendar and it would not be convenient for the users if NCDataset would return them as `NCDatasets.DateTimeStandard` instead of `Dates.DateTime` (which is more complete and has better support for 3rd party packages). Likewise I implemented a equivalent conversion for writing data.

**Comment by rafaqz** [comment]
Ah ok I misunderstood. Standard calendars will convert automatically to regular DateTime. But DatTime360day etc will remain as and work both ways.
