### ISSUE TITLE
Read a variable of Char Datatype

### ISSUE THREAD

**Issue by briochemc** [Alexander-Barth/NCDatasets.jl#39]
How can I read a variable made of `Char`s?

I am trying to read a NetCDF file from [GEOTRACES](https://www.bodc.ac.uk/geotraces/data/idp2017/) that contains a variable for cruise names. This variable seems to be encoded as an array of `Char`s, but I don't know how to acces it. After reading the NetCDF file via `ds  = Dataset("...")` (I think the file is too big to be put in a MWE here), I get:
```julia
julia> ds["metavar1"]
metavar1 (6 × 1866)
  Datatype:    Char
  Dimensions:  STRING6 × N_STATIONS
  Attributes:
   long_name            = Cruise
   _FillValue           =

julia> size(ds["metavar1"])
(6, 1866)

julia> ds["metavar1"][:,:]
ERROR: MethodError: no method matching isnan(::String)
Closest candidates are:
  isnan(::BigFloat) at mpfr.jl:886
  isnan(::Missing) at missing.jl:79
  isnan(::Float16) at float.jl:530
  ...
Stacktrace:
 [1] getindex(::NCDatasets.CFVariable{Union{Missing, Char},2,NCDatasets.Variable{Char,2},NCDatasets.Attributes}, ::Colon, ::Colon) at /Users/benoitpasquier/.julia/packages/NCDatasets/uW2kc/src/NCDatasets.jl:1304
 [2] top-level scope at REPL[187]:1
```

I can overload `isnan` with `Base.isnan(::String) = false` for this to works but it feels wrong... Maybe it's possible/better to dispatch NCDataset's `getindex` to another method if the element type is `String` or `Char`?

**Comment by Alexander-Barth** [comment]
I do not have code snipped reproducing this issue at hand, but I belief that my recent commit address should fix this issue. Can you try?

**Comment by briochemc** [comment]
Yes, your commit worked! Thanks! And good job on figuring out the type of `_FillValue` was the culprit! (I figured it out eventually and regretted not having looked at your commit earlier...)

Not that I will use it, but here is a MWE that I was trying to build to recreate the file.

```julia
using NCDatasets
ds = Dataset("/tmp/test.nc", "c")
defDim(ds, "lon", 2)
defDim(ds, "lat", 2)
v = defVar(ds, "Char variable", Char, ("lon","lat"))
v[:,:] = ['a' 'b'; 'c' 'd']
v.attrib["_FillValue"] = ""
close(ds)
```

Using a string for `_FillValue` (the `v.attrib["_FillValue"] = ""` line) currently fails with
```julia
ERROR: attributes can only be scalars or vectors
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] nc_put_att(::Int32, ::Int32, ::String, ::Missing) at /Users/benoitpasquier/.julia/packages/NCDatasets/2vobE/src/netcdf_c.jl:541
 [3] setindex!(::NCDatasets.Attributes, ::Missing, ::String) at /Users/benoitpasquier/.julia/packages/NCDatasets/2vobE/src/NCDatasets.jl:305
 [4] top-level scope at REPL[40]:1
```
but it sounds like you would need something like that to be able to CI-test the latest commit.

**Comment by Alexander-Barth** [comment]
In fact, for julia `""` is a string, for a character one should use single quotes e.g. `' '` (the space character). The fill value should be defined before the data, otherwise the NetCDF library will give the following error message:

```
ERROR: NCDatasets.NetCDFError(-122, "NetCDF: Attempt to define fill value when data already exists.")
``` 

One can either define the `fillvalue` when the variable is created: 
```julia
v = defVar(ds, "Char variable", Char, ("lon","lat"), fillvalue = ' ')
```

Or before the data is written variable by the setting it:

```julia
v = defVar(ds, "Char variable", Char, ("lon","lat"))
v.attrib["_FillValue"] = ' '
v[:,:] = ['a' 'b'; 'c' 'd']
close(ds)
```

In any case, thank you very much for the reproducing code. I will add it to the test suite! It helps me a lot when the users go this extra mile.

**Comment by briochemc** [comment]
No worries! 

Yes I know that strings are double quoted and characters single quoted, I just copied what the GEOTRACES NetCDF file that bugged me in the first place had in it. I agree that it's inconsistent to have a fill value type different than the element type of the data, but as I said, they did not even use that `""` fill value and filled the data with `'\0'`s instead...

**Comment by Alexander-Barth** [comment]
OK, is there still an open issue related to `NCDatasets.jl`  as opposed to the NetCDF file?

**Comment by briochemc** [comment]
Nope, closed!
