### ISSUE TITLE
Accessing variable in loaded dataset leads to kernel dying

### ISSUE THREAD

**Issue by brynpickering** [Alexander-Barth/NCDatasets.jl#4]
Hi, I've jut come across NCDatasets as a much cleaner way of dealing with NetCDF files than the NetCDF package. However, on loading a file into Julia and accessing a variable, the whole kernel dies!

Current usage: 

```
Using NCDatasets; dataset = Dataset("test_netcdf.nc")
dataset["varname1"] 
```

Pretty simple. The netcdf is only 80kb in size, the variable I was trying to access has 32 elements over one dimension.

**Comment by Alexander-Barth** [comment]
Can you make this file available to me?

**Comment by Alexander-Barth** [comment]
Which version of NCDatasets and Julia are you using, and on which OS do you have?

**Comment by brynpickering** [comment]
Julia: 0.6.0
NCDatasets: 0.0.3
OS: Windows 64bit

File can be found here: https://www.dropbox.com/s/gof1bwe337za068/test_netcdf.nc?dl=0

**Comment by Alexander-Barth** [comment]
Thanks for the file and the info. On which variable name do you have this error and can you send me the full error message?
It works for me with the variables that I have tested (on Linux 64-bit):

```
julia> using NCDatasets; dataset = Dataset("test_netcdf.nc");

julia> dataset["carrier_ratios"]
carrier_ratios (3 × 4 × 1)
  Datatype:    Float64
  Dimensions:  carrier_tiers × resources × loc_techs_conversion_plus
  Attributes:
   _FillValue           = NaN

julia> dataset["time"]
time (48)
  Datatype:    Int64
  Dimensions:  time
  Attributes:
   units                = hours since 2005-07-01 00:00:00
   calendar             = proleptic_gregorian

julia> dataset["color"]
color (16)
  Datatype:    String
  Dimensions:  techs
```
Are there some strings in the NetCDF file which contain non-Ascii characters? If yes, which encoding do they use?

I notice that you are using NaN as fillvalues. In the current release, NCDatasets handels them inconsistently. I just updated NCDatasets to correct for this issue. However, it is unlikely that this is actually the issue you are seeing. It is probably something else, but still can you update NCDatasets using these command and try again?  

https://github.com/Alexander-Barth/NCDatasets.jl#latest-development-version

Can you send me also the output of this command?

```julia
Pkg.test("NCDatasets")
```

**Comment by brynpickering** [comment]
1. There is no error message, the kernel simply dies.

2. I can successfully run the commands you are showing, but on trying to index a string array (e.g. "color"), the kernel will die. In the Jupyter notebook, the output is actually the array e.g.

```
dataset["time"]

48-element NCDatasets.CFVariable{Int64,Float64,1}:
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 2005-07-01T00:00:00
 ⋮                  
```
The kernel will die on calling any array of strings in the notebook (unlike in the command line, which will die when indexing that array). So there seems to be a problem with processing the strings.

2. No non-ASCII characters.

3. Updated to development version

4. All tests pass

p.s. note the lack of time increase in the time variable, I'll start this up as another issue ;)

**Comment by Alexander-Barth** [comment]
Here too, I could reproduce this issue and committed a fix. Does it now work for you?  (after running `Pkg.update()`)

I get this for the color variables in IJulia:
```
dataset = Dataset("/home/abarth/Downloads/test_netcdf.nc"); color = dataset["color"]
```

```
16-element NCDatasets.CFVariable{String,String,1}:
 "#7e7a36"
 "#bc7967"
 "#7e7a36"
 "#666666"
 "#bc7967"
 "#185b48"
 "#99CB48"
 "#d486af"
 "#666666"
 "#bc7967"
 "#3c7632"
 "#19122b"
 "#17344c"
 "#caa9e7"
 "#7e7a36"
 "#7e7a36"
```

**Comment by brynpickering** [comment]
Yup, that does the trick!
