### ISSUE TITLE
Data typed Union{Missing, Dates.DateTime, AbstractCFDateTime, Number} when calling discrete indices

### ISSUE THREAD

**Issue by aramirezreyes** [Alexander-Barth/NCDatasets.jl#40]
I have a NetCDF file called "timeSlab_2d.nc". When trying to obtain one index or a range, the element type of the returned array is `Union{missing, Float32}`. However, when trying to get a 'discrete' set of indices, the element type of the returned array is `Union{Missing, Dates.DateTime, AbstractCFDateTime, Number}`.

First of all: excuse me for not providing a self-contained example (by not providing the file). How can I provide a self-contained example in the future?

Example:
```
julia> ds = Dataset("timeSlab_2d.nc");
julia> ds["x"]
x (128)
  Datatype:    Float32
  Dimensions:  x
  Attributes:
   units                = m

julia> ds["x"][1:5]
5-element Array{Union{Missing, Float32},1}:
      0.0f0
  40000.0f0
  80000.0f0
 120000.0f0
 160000.0f0

julia> ds["x"][[1,3,5]]
3-element Array{Union{Missing, Dates.DateTime, AbstractCFDateTime, Number},1}:
      0.0f0
  80000.0f0
 160000.0f0
```
**Expected behavior**

I would expect the returned array in all the cases to be of type:

```
Array{Union{missing,Float32},1}
```

**Environment**

 -Julia Version 1.3.0-rc4.1
Commit 8c4656b97a (2019-10-15 14:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = /Applications/Emacs.app/Contents/MacOS/Emacs "$@"

[85f8d34a] NCDatasets v0.9.5

**Comment by rafaqz** [comment]
Was just about to report this too.

**Comment by Alexander-Barth** [comment]
The tool `ncgen` can be used to create a NetCDF file similar to yours to provide a self-contained reproducing example. The additional benefit (for all) is that I can use these problematic code in a test-suite once it is fixed and avoid regressions in the future. But for this case, it is not necessary (but thanks for asking!).

The difference here is that the `getindex` function of `ds["x"][1:5]` is handled directly by `NCDatasets` while the `getindex` function `ds["x"][[1,3,5]]` is the generic `getindex` function from Julia. The later is functional but can be very slow (like fetching all elements individually).

To use the generic Julia `getindex` function, the type of the variable must be known before-hand (once the NCDatasets.CFVariable is created). But the effective type does also depend on the attributes like `scale_factor`, `add_offset`, `units` and `calendar` which can be modified later. For example you define a variable `Temperature` of type `Int16`¸ then initially any indexing is a `Union{Missing,Int16}`. But if you add a `scale_factor` with the value `0.1`, then any indexing should be a `Union{Missing,Float64}`. 

Maybe for files open in read-only mode, we can already determine the values and types of these attributes (`scale_factor`, `add_offset`, `units` and `calendar`) add this stage:

https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/src/NCDatasets.jl#L956

To make a better decision on the return type. Note the problem would persists for file in read-write mode. Any ideas would be appreciated.

**Comment by Alexander-Barth** [comment]
This issue is now fixed in master. Thank you for reporting it.

**Comment by aramirezreyes** [comment]
Great, thanks!
