### ISSUE TITLE
conflict of netcdf.dll

### ISSUE THREAD

**Issue by JianghuiDu** [Alexander-Barth/NCDatasets.jl#41]
When `using MATLAB` the netcdf library is pointed to `netcdf.dll` in the MATLAB installation folder and `NCDatasets` reports 
```
error compiling nc_open: could not load library "C:\Users\Jianghui\.julia\conda\3\Library\bin\netcdf.DLL"
The specified module could not be found.
```
How could I redirect the library?

**Comment by Alexander-Barth** [comment]
You could try to hard-code the path in `~/.julia/dev/NCDatasets/deps/deps.jl` (the location of this file will be different on windows). You can try the one provided by conda and the one by Matlab.

```
[...]
# Load dependencies
@checked_lib libnetcdf "/full/path/to/netcdf/library"
```

Maybe `MATLAB.jl` change some environment variables. I suggest you to ask also the julia form and MATLAB.jl . I do not use Windows and Matlab anymore.

**Comment by Alexander-Barth** [comment]
Did you see this issue [1] and the discussion thread [2]? I think it is not possible currently to load two different versions of netcdf library at the same time. Maybe the work-around of [2] can also be applied here.

[1] https://github.com/JuliaIO/ImageMagick.jl/issues/142
[2] https://discourse.julialang.org/t/initerror-for-a-combination-of-imagemagick-and-matlab/16869?u=yakir12

**Comment by JianghuiDu** [comment]
Thanks! I was thinking about a quick fix.  It doesn't really worth the effort.  Won't call Matlab in Julia anymore.
