### ISSUE TITLE
Something is wrong with `mean`: takes too much time

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#48]
**Describe the bug**

Calling `mean` on a NCDataset seems to take too much time. Much more than when applied to the direct array representation.

**To Reproduce**
Let's say I have:
```
julia> fld
toa_sw_all_mon (360 × 180 × 228)
  Datatype:    Float32
  Dimensions:  lon × lat × time
  Attributes:
   long_name            = Top of The Atmosphere Shortwave Flux, All-Sky conditions, Monthly Means     
   standard_name        = TOA Shortwave Flux - All-Sky
   CF_name              = toa_outgoing_shortwave_flux
   comment              = none
   units                = W m-2
   valid_min            =       0.00000
   valid_max            =       600.000
   _FillValue           = -999.0

julia> fldarray = Array(fld);
```
Then I do:
```
julia> mean(fldarray)
102.24223f0
```
which is instant. However, 
```
julia> mean(fld)
```
takes way too long (I always have to terminate Julia process). The same story goes for using `dim(fld; dims = 3)`...

**Expected behavior**

`mean` should take almost as much time as in the Array version.

**Comment by Datseris** [comment]
Even with #49 resolved, this is still an issue for me.

**Comment by ctroupin** [comment]
When you do 
`julia> mean(fld)`
I guess it cannot work because of the type of `fld` is something like:
```
NCDatasets.CFVariable{Union{Missing, Dates.DateTime, AbstractCFDateTime, Number},2,NCDatasets.Variable{Int16,2},NCDatasets.Attributes}
```
and the function `mean` is not defined for this type.
`julia> mean(fld[:])`
should work.

**Comment by Datseris** [comment]
I see. Should we make this a feature request then, so that common functions like `sum, mean`, etc. dispatch on `CFVariable` by simply propagating `Array(fld)` to the other functions?

**Comment by Datseris** [comment]
Also, still, I don't get why the freeze happens. Julia should through immediatelly a method error if a method doesn't exist. Are you sure there isn't something else going on in the source code? Because I can see:
```julia
julia> @which mean(fld)
mean(A::AbstractArray) in Statistics at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\Statistics\src\Statistics.jl:157
```

**Comment by Datseris** [comment]
My guess is that `mean` tries to iterate naively each value of the `CFVariable` one by one, but that could be terribly inefficient.

**Comment by Alexander-Barth** [comment]
> My guess is that `mean` tries to iterate naively each value of the `CFVariable` one by one, but that could be terribly inefficient.

Yes, I think that this is the case. It would be interesting to see if the CPU time is mostly spent in the netCDF C libary or in `NCDatasets.jl`. As far I understand, the netCDF implements a cache (https://www.unidata.ucar.edu/software/netcdf/workshops/most-recent/nc4chunking/Cache.html) but maybe only if the data is "chunked" ? If we cannot rely on the caching in the netCDF C library, maybe a solution would be a caching array type? For a 2 x 3 x 4 array, it would entire slices of say 2 x 3 x 1 and keep them in cache? Similar to [sizehint!](https://docs.julialang.org/en/v1/base/collections/#Base.sizehint!) we could have cachehint!.
