### ISSUE TITLE
[DOC] How to get the dimensions of a dataset?

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#50]
I have
```julia
julia> fld
toa_sw_all_mon (360 × 180 × 228)
  Datatype:    Float32
  Dimensions:  lon × lat × time
  Attributes:
   long_name            = Top of The Atmosphere Shortwave Flux, All-Sky conditions, Monthly Means     
   standard_name        = TOA Shortwave Flux - All-Sky
   CF_name              = toa_outgoing_shortwave_flux
   comment              = none
   units                = W m-2
   valid_min            =       0.00000
   valid_max            =       600.000
   _FillValue           = -999.0
```

how do I programmatically get the sequence `lon × lat × time`, which are the dimensions of the dataset? I'd like to be able to get them both as the direct variables of the NCFile, but also as just a tuple of names `(:lon, :lat, :time)`.

**Comment by Alexander-Barth** [comment]
Currently we have `dimnames` which returns a tuple of strings. I just clarified in the documentation that it can also be used for `CFVariable`s.

**Comment by Datseris** [comment]
Thanks, this is very useful to know! Would you accept some documentation improvements as well? I think the docs could benefit by being structured in different pages. Docs is the thing a newcomer can help the most, because they (in this case me) see the code from a fresh perspective, and someone that has been deep into development of a package may not immediatelly see what is clear and what is not.
