### ISSUE TITLE
Why is CFVariable a subtype of `AbstractArray`?

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#51]
(since I want to contribute here regularly, I need to understand some design decisions)

Problems like e.g. #48 arise because `CFVariable` is a subtype of `AbstractArray`, even though it in fact does not represent a contiguous blob of numbers that are stored in-memory. If I understood it properly, a `CFVariable` represents data on disk that are not yet loaded on memory, correct?

What parts of `NCDatasets` uses the fact that `CFVariable` is a subtype of `AbstractArray`?

**Comment by Alexander-Barth** [comment]
To my understanding `AbstractArray` is for anything array-like and not necessarily "a contiguous blob of numbers that are stored in-memory", but I might be wrong.

I noticed that in the HDF5.jl package, their variable type (called HDF5Dataset) is not a subtype of `AbstractArray`. Such type of indexing does not work consequently:

```julia
using HDF5
c = h5open("/home/abarth/Downloads/c3d_after_pca.hdf5")
a = c["/video_test_0000526/c3d_features"]
size(a)
# returns (500, 1418)
a[CartesianIndex(1,1)]
# ERROR: MethodError: no method matching getindex(::HDF5Dataset, ::CartesianIndex{2})
a[[1,2,3],:]
# ERROR: MethodError: no method matching getindex(::HDF5Dataset, ::Array{Int64,1}, ::Colon)
```
They do work with `CFVariables` (but again loading every element individually). 

Some other package might implement a function which accepts any array-like parameter. If the parameter type is declared as `AbstractArray` then a `CFVariable` can be used.

But I have to say, that I do not have the full-picture in my mind of what would happen if we stop `CFVariable` to derive from `AbstractArray`. There might be other issues.

**Comment by Datseris** [comment]
Since NCDatasets is not yet in 1.0, this is something to consider.

So far, I have been porting a Python code in Julia that heavily manipulates CFVariables loaded from a nc file. I've noticed that almost all their operations between and on CFVaribles leave  the type unchanged.

For example, if you did `field.mean(axis = 1)` in Python (where `field` is a variable loaded from a NC file through the `xarray` package), then the result will still be an `xarray`. This is not possible here, which is why I've been thinking of implementing hand-rolled versions of `mean, sum`, etc, that dispatch directly on `CFVariable`  and not on `Array`.

Have you every used the `xarray` library btw? I could open an issue showing some seriously cool features they have which I couldn't reproduce with `NCDatasets` so far.

**Comment by Datseris** [comment]
Ah sorry, I've _now_ read your post in https://github.com/Alexander-Barth/NCDatasets.jl/issues/47#issuecomment-571305875 , so you have had a look at `xarray` by now.

**Comment by Alexander-Barth** [comment]
> Have you every used the xarray library btw? I could open an issue showing some seriously cool features they have which I couldn't reproduce with NCDatasets so far.

I belief that this would still be useful if you have time to do so. I have some very superficial knowledge of `xarray`.

**Comment by Datseris** [comment]
Okay, I will be opening separate issues then, that will be like Feature Requests about something that `xarray` does and would be cool to be here.

A comment on:

> Some other package might implement a function which accepts any array-like parameter. If the parameter type is declared as AbstractArray then a CFVariable can be used.

Well, if we really think about it, is this really true? Can a `CFVariable` really be used in such a context without a problem? Because the discussion in #48 is targeting this question. 

I wonder whether it would be simpler to just motivate users to just call `Array(v)` when they want to use `v` as an array.

**Comment by Alexander-Barth** [comment]
> Well, if we really think about it, is this really true? Can a `CFVariable` really be used in such a context without a problem? Because the discussion in #48 is targeting this question.

Yes, you only need to avoid loading element per element.
