### ISSUE TITLE
Quick question on scale_factor and add_offset

### ISSUE THREAD

**Issue by natgeo-wong** [Alexander-Barth/NCDatasets.jl#56]
Sorry, but I couldn't find this in the documentation.

Is there a way to set `scale_factor` and `add_offset` to variables?  Do they go under attributes or are they keyword arguments?

**Comment by Alexander-Barth** [comment]
They are just regular attributes. I would recommend to set them in `defVar`:

```julia
defVar(ds, ..., attrib = [
   "scale_factor" => 10.,
   "add_offset" => -1.,
])
```

http://cfconventions.org/cf-conventions/cf-conventions.html#_reduction_of_dataset_size
