### ISSUE TITLE
Use Yggdrasil as a provider for the NetCDF library instead of Conda

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#61]
We have to wait for JuliaPackaging/Yggdrasil#329 and references therein to be resolved first.

(thankfully this is non-breaking)

**Comment by Alexander-Barth** [comment]
Should be fixed with https://github.com/Alexander-Barth/NCDatasets.jl/pull/88 (thanks to @virs)
