### ISSUE TITLE
Can one obtain the dimensions directly from a dataset?

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#63]
at the moment we have:
```
julia> typeof(EBAF)
Dataset

julia> typeof(v)
NCDatasets.CFVariable{Union{Missing, Dates.DateTime, AbstractCFDateTime, Number},3,NCDatasets.Variable{Float32,3},NCDatasets.Attributes}

julia> dimnames(v)
("lon", "lat", "time")

julia> dimnames(EBAF)
ERROR: MethodError: no method matching dimnames(::Dataset)
```
which should otherwise be possible, since even the pretty printing of `Dataset` displays the dimensions.

**Comment by Alexander-Barth** [comment]
Yes, this is possible with `keys(ds.dims)` (likewise of `keys(ds.group)` and `keys(ds.attrib)` for groups and global attributes). `ds.dim`, `ds.group` and `ds.attrib` are all similar to dictionaries.

**Comment by Datseris** [comment]
Shouldn't we just extend `dimnames` to do `keys(ds.dim)`?

**Comment by Alexander-Barth** [comment]
The `keys(ds.dim)` is now (better) documented. I prefer to not add redundant ways to  achieve the same thing. (This is one of the reasons, in my humble opinion, why Python got so much more popular than Perl; I used both, and Perl was not fun).
