### ISSUE TITLE
Printing problems in Juno

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#65]
Let's say I load a dataset:
```
ncdir = datadir("CERES", "CERES_EBAF_TOA.nc")
TOA = NCDataset(ncdir)
times = TOA["time"]
```

If I do the command `times = TOA["time"]` via Juno's inline evaluation, there is a problem. The following are printed in the REPL console (notice, not inline):
```
julia> time (231)
  Datatype:    Int32
  Dimensions:  time
  Attributes:
   long_name            = time
   units                = days since 2000-03-01 00:00:00
   delta_t              = 0000-00-01 00:00:00
```
while the inline printing gets:
```

231-element NCDatasets.CFVariable{Union{Missing, DateTime, AbstractCFDateTime, Number},1,NCDatasets.Variable{Int32,1},NCDatasets.Attributes}:
 2000-03-15T00:00:00
 2000-04-15T00:00:00
 2000-05-15T00:00:00
 2000-06-15T00:00:00
 2000-07-15T00:00:00
 2000-08-15T00:00:00
 2000-09-15T00:00:00
 2000-10-15T00:00:00
 2000-11-15T00:00:00
 2000-12-15T00:00:00
```

There has to be something wrong with passing the "correct" IO around, and at some point the `stdout` is passed instead... Alas, I've read the pretty printing source many times, but couldn't find the problem.

![image](https://user-images.githubusercontent.com/19669089/72799977-a0b7d180-3c46-11ea-9bc2-c7b963639850.png)

**Environment**
Latest Master, latest stable from Julia/Juno. Windows 10.

**Comment by Alexander-Barth** [comment]
I cannot (or rather no longer) reproduce this problem with Juno 0.8.2 and NCDatasets 0.10.2.
It seems to be fixed. Let me know if the problem persists for you.

![Bildschirmfoto von 2020-06-30 14-15-44](https://user-images.githubusercontent.com/9881475/86125113-6cd9b580-badc-11ea-922c-9a83a5df925c.png)
