### ISSUE TITLE
Question: Is it possible to obtain the dimension _values_ from a CFVariable?

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#69]
Let's say that I have selected a CFVariable from a file. Is it possible to get the dimension _values_ from this variable?

I mean, imagine I (for some reason) _don't_ have a variable binding to the toplevel `nc` file. Can I still do what I ask, or it is impossible?

**Comment by Alexander-Barth** [comment]
I like to make the distinction between dimensions (which have just a length) and the coordinate variable (which can have the same name of the dimensions or not). This difference is evident when you work with grids who are rotated relative to longitude/latitude (where it does not make sense to share the same name and the coordinate variables have more than just 1 dimension). I think that this is an important distinction which motivates also how I structured `NCDatasets`.

The function `coord` allows you to get the coordinate variable by using the CF standard name.

But in any case, you can always recover the toplevel dataset from a CFVariable, like this:

```
julia> v = NCDataset("dataset.nc")["v1"]
v1 (1000 × 500 × 31)
  Datatype:    UInt8
  Dimensions:  longitude × latitude × time
  Attributes:
   add_offset           = 1.0
   scale_factor         = 5.0

julia> NCDataset(v)
NCDataset: dataset.nc
Group: /

Dimensions
   longitude = 1000
   time = 31
   latitude = 500

Variables
  v1   (1000 × 500 × 31)
    Datatype:    UInt8
    Dimensions:  longitude × latitude × time
    Attributes:
     add_offset           = 1.0
     scale_factor         = 5.0
```
