### ISSUE TITLE
Ability to not apply `add_offset` and `scale_factor`

### ISSUE THREAD

**Issue by natgeo-wong** [Alexander-Barth/NCDatasets.jl#70]
Hi!

I was just wondering if it was possible to request for an option to not apply `add_offset` and `scale_factor` during NetCDF extraction, but instead read in the raw values.

This is because sometimes, values are packed into `Int32` formats (e.g. for reanalysis data) to save space and memory.  And sometimes I would just want to perform basic operations and resave analysed data into another file, and this can be done using the raw `Int32` format instead of converting it to `Float64` and having it occupy a lot more space on computer memory (around 8x).

The default could always be the unpacking of the data format using `add_offset` and `scale_factor`, but I was just wondering if the ability to not apply them could be specified if need be.

I currently can do this using NetCDF.jl, because NetCDF.jl doesn't automatically apply the above, but I'm not sure how much longer this would be done, because it's considered a bug (i.e. all the many issues that have come up regarding this).

Cheers!  Sorry for the relatively weird request.

**Comment by Alexander-Barth** [comment]
Yes, you can do this. Be assured, this is not an unreasonable request :-)

In the documentation, there is an example for this:
https://alexander-barth.github.io/NCDatasets.jl/latest/#Load-a-netCDF-file-1

```julia
# The mode "r" stands for read-only. The mode "r" is the default mode and the parameter can be omitted.
ds = NCDataset("/tmp/test.nc","r")
v = ds["temperature"]

# load a subset
subdata = v[10:30,30:5:end]

# load all data
data = v[:,:]

# load all data ignoring attributes like scale_factor, add_offset, _FillValue and time units
data2 = v.var[:,:]


# load an attribute
unit = v.attrib["units"]
close(ds)
```

**Comment by natgeo-wong** [comment]
Oooooh I must have missed that I'm sorry.
But this is good to know!!!
Closing the issue.  Thanks so much for your patience.
