### ISSUE TITLE
How to get the bounding box?

### ISSUE THREAD

**Issue by rafaqz** [Alexander-Barth/NCDatasets.jl#71]
Is there an easy way to retrieve the outer bounds of a netcdf dimension? I'm also not sure how consistently the bounds are included in netcdf files.

**Comment by Alexander-Barth** [comment]
I would just read the lon / lat coordinate variables for this. Some netcdf include this information also in global attributes but I am not aware that this is mandatory under the CF convention.

**Comment by rafaqz** [comment]
Interesting. I have seen "bnds" variables that hold the bounds, but not consistently. The problem is knowing the exact size of the last cell when the data represents the mean value over an interval.

**Comment by Alexander-Barth** [comment]
NCDatasets does not do anything special with the `bounds` attributes. If you think it should, I would be happy to review PRs.

**Comment by rafaqz** [comment]
Seems like it's not a standard thing. I'll just use it in GeoData.jl if it's there.
