### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by natschil** [Alexander-Barth/NCDatasets.jl#75]
Thanks first of all for the great package! I'm running into surprisingly high memory usage together with NCDatasets which I'm trying to get to the bottom of. This is relevant to me because memory issues related to loading data seem to be preventing me from running things  in the cloud where memory is expensive. I suspect my main problem to be somehow related to how I load my data, The resulting object is, say, 7MB large but julia memory usage aftewards is (much) higher. I load my data with `NCDatasets.nomissing(d["latitude"][:], NaN)`, if there are more efficient ways to do this please let me know. However, it was hard to create a minimal working example as it seems like not all dataset types led to this behaviour (my data comes as Int32s that are interpreted as floats, not sure how to create a sample dataset like this). In trying to reproduce this issue, I came across the following strange behaviour that I did not understand.

First, I created a dataset, this is about 16M large
```
Dataset("file.nc", "c", attrib = ["title" => "sample netCDF file"]) do ds
          defVar(ds,"vgos",Float32.(rand(2000,2000,1)),("lon","lat","t") )
       end;
```
Then, I restarted julia and loaded the Dataset

```
using NCDatasets
d = Dataset("file.nc")
GC.gc()
```
At this point, julia uses about 220MB of memory on my machine. Now I read in the dataset and then delete everything
```
vs = NCDatasets.nomissing(d["vgos"][:],NaN)
close(d)
vs=nothing
d=nothing
GC.gc()
````
Now memory usage has jumped to 238MB, and I do not understand why. 

I'm running this on Fedora with julia 1.2 with NCDatasets v0.9.5, but the machines I originally saw suspiciously high memory usage on were running julia 1.3.

**Comment by Alexander-Barth** [comment]
Does the memory incease if you run this in a loop?

```julia
using NCDatasets
d = Dataset("file.nc")
GC.gc()
vs = NCDatasets.nomissing(d["vgos"][:],NaN)
close(d)
vs=nothing
d=nothing
GC.gc()
```

**Comment by natschil** [comment]
Perhaps this is actually related to details of  julia's garbage collection. Running the above in a loop (e.g. 10 times) causes a final memory footprint of 287MB (compared with 222MB initially).

Weirdly enough, the first time I ran this in the loop it  jumped back to 222MB  after calling GC.gc() outside the loop.  I tried reproducing this  behaviour several times afterwards and couldn't. I really don't see why julia allocates 287-222 = 65 MB   of memory to read a 7MB file several times.

**Comment by natschil** [comment]
Note that calling 
```
for i in 1:100
    vs = rand(Float32, (2000,2000,1))
    println(vs[10])
    vs = nothing
    GC.gc()
    sleep(0.01)
end
```
results in no memory being left over at the end.

**Comment by Alexander-Barth** [comment]
I ran this loop 1000 times and the memory usage remained constant after the first few iterations. If there is a memory leak inside NCDatasets this number would have gone up at every iteration.

```julia
 for i = 1:1000
         @show i
         d = Dataset("file.nc")
         GC.gc()
         vs = NCDatasets.nomissing(d["vgos"][:],NaN)
         close(d)
         vs=nothing
         d=nothing
         GC.gc()
       end
```

This is the stabilized memory usage  that I see:

```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     ZEIT+ BEFEHL
 3643 abarth    20   0 1323964 373836 126916 S   0.0  1.1   2:22.76 julia
```

> Note that calling ...
> results in no memory being left over at the end.

This is quite interesting that you are able to produce the issue independently of NCDatasets. I would suggest you to make a post on a julia discourse about this.

Also have a look at `NCDatasets.load!` for loading in-place.

```julia
ds = Dataset("file.nc")
ncv = ds["vgos"].var;
data = zeros(eltype(ncv),size(ncv));
NCDatasets.load!(ncv,data,:,:,:)
close(ds)
```

**Comment by natschil** [comment]
I didn't know about `load!` that sounds like a very useful function. The documentation doesn't mention anything about how missing data is treated. Is is possible to give ranges other than `:` (e.g. `500:300`) to `load!` ?

**Comment by Alexander-Barth** [comment]
> I didn't know about `load!` that sounds like a very useful function. The documentation doesn't mention anything about how missing data is treated.

Missing values are not handled by this function. They are returned as they are in the netcdf file and no scaling is applied.

> Is is possible to give ranges other than `:` (e.g. `500:300`) to `load!` ?

Yes, but just ranges (possibly with an step different from one)

**Comment by natschil** [comment]
Thanks for the information! My data is 2-dimensional, but being able to specify a (1d) range should already make it possible to exclude large parts of it.
