### ISSUE TITLE
Feature request: `attributes(x)` returns a dictionary.

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#76]
```
julia> x = TOA["toa_sw_all_mon"]
toa_sw_all_mon (360 × 180 × 231)
  Datatype:    Float32
  Dimensions:  lon × lat × time
  Attributes:
   long_name            = Top of The Atmosphere Shortwave Flux, All-Sky conditions, Monthly Means
   standard_name        = TOA Shortwave Flux - All-Sky
   CF_name              = toa_outgoing_shortwave_flux
   comment              = none
   units                = W m-2
   valid_min            =       0.00000
   valid_max            =       600.000
   _FillValue           = -999.0
```

Since this information is what is exposed to the user, obtaining it programmatically should be straightforward, something like `attributes(var)` should return the dictionary that is printed. 

At the moment one has to do `x.attrib["units"]` but one can only do it one by one.

**Comment by Alexander-Barth** [comment]
`x.attrib` is behaves already like a dictionary. You can use `Dict(x.attrib)` if you want a in-memory representation of it.
