### ISSUE TITLE
[DOC] How to merge 2 NCDatasets (same dims/attributes)

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#77]
I have two `.nc` files which I load into 2 `NCDataset`s. Both files come from the same dataset (CERES EBAF), and have identical global attributes as well as dimensions.

I am looking for a simple way to merge these two into one `NCDataset`, but I can't figure out a simple way to do this. I imagine it is possible by re-creating every single variable via `defVar`, but there are a lot of them... is there any simpler way?

**Comment by Balinus** [comment]
I think you can simply pass an `Array{String}` to Dataset function

```julia
using Glob
files = glob("*.nc")
ds = Dataset(files)
```
c.f. https://github.com/Alexander-Barth/NCDatasets.jl/issues/16

**Comment by Datseris** [comment]
This doesn't seem to work for me:
```
CERES = [datadir("CERES", "CERES_EBAF_$(X).nc") for X in ("TOA", "SFC", "CLD")]

julia> NCDataset(CERES)
ERROR: BoundsError: attempt to access 0-element Array{String,1} at index [1]
Stacktrace:
 [1] getindex at .\array.jl:744 [inlined]
 [2] #NCDataset#43(::Nothing, ::Bool, ::Type{NCDataset}, ::Array{String,1}, ::String) at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\multifile\functions.jl:42
 [3] NCDataset at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\multifile\functions.jl:20 [inlined] (repeats 2 times)
 [4] top-level scope at none:0
```

**Comment by Datseris** [comment]
Yeap, even if I try from another computer and with different names, this functionality is bugged.

**Comment by Datseris** [comment]
I am also trying to use `setindex!` and loop over the variables, like so:
```
ceresall["toa_sw_all_mon"] = ceres["toa_sw_all_mon"]
ERROR: MethodError: no method matching setindex!(::NCDataset, ::NCDatasets.CFVariable{Union{Missing, Float32},3,NCDatasets.Variable{Float32,3},NCDatasets.Attributes,NamedTuple{(:fillvalue, :scale_factor, :add_offset, :calendar, :time_origin, :time_factor),Tuple{Float32,Nothing,Nothing,Nothing,Nothing,Nothing}}}, ::String)
Stacktrace:
 [1] top-level scope at none:0
```
where `ceresall` is the open NCDataset (in append mode) and `ceres` is another file whose variables I want to merge into `ceresall`. 

Using `defVar` also doesn't work in the way I would expect it:
```
julia> defVar(ceresall, ceres["toa_sw_all_mon"])
ERROR: MethodError: no method matching defVar(::NCDataset, ::NCDatasets.CFVariable{Union{Missing, Float32},3,NCDatasets.Variable{Float32,3},NCDatasets.Attributes,NamedTuple{(:fillvalue, :scale_factor, :add_offset, :calendar,
:time_origin, :time_factor),Tuple{Float32,Nothing,Nothing,Nothing,Nothing,Nothing}}})
Closest candidates are:
  defVar(::NCDataset, ::Any, ::DataType, ::Any; kwargs...) at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\variables.jl:135
  defVar(::NCDataset, ::Any, ::AbstractArray{Union{Missing, nctype},N}, ::Any; kwargs...) where {N, nctype<:Union{Float32, Float64, Int16, Int32, Int64, Int8, UInt8}} at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\variables.jl:196
  defVar(::NCDataset, ::Any, ::AbstractArray{#s135,N} where #s135<:Union{Missing, nctype}, ::Any; kwargs...) where {N, nctype<:Union{DateTime, AbstractCFDateTime}} at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\variables.jl:207
  ...
Stacktrace:
 [1] top-level scope at none:0
```

So my question is simple now: Given that I already have a `CFVariable`, how do I append it into a NCDataset? Is the only way is to write down all attributes of the variable one by one? @Alexander-Barth  ?

**Comment by Datseris** [comment]
Hm, I've found a solution that iterates and merges all variables.

```
julia> merge(ceresall, ceres)
Porting variable toa_lw_all_mon...
Porting variable toa_net_all_mon...
Porting variable toa_sw_clr_c_mon...
Porting variable toa_lw_clr_c_mon...
Porting variable toa_net_clr_c_mon...
Porting variable toa_sw_clr_t_mon...
Porting variable toa_lw_clr_t_mon...
Porting variable toa_net_clr_t_mon...
Porting variable toa_cre_sw_mon...
Porting variable toa_cre_lw_mon...
Porting variable toa_cre_net_mon...
Porting variable solar_mon...
ERROR: NCDatasets.NetCDFError(-62, "NetCDF: One or more variable sizes violate format constraints")
Stacktrace:
 [1] check at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\errorhandling.jl:29 [inlined]
 [2] nc_enddef at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\netcdf_c.jl:986 [inlined]
 [3] datamode at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\dataset.jl:139 [inlined]
 [4] setindex!(::NCDatasets.Variable{Float32,3}, ::Array{Float32,3}, ::Colon) at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\indexing_in_vars.jl:61
 [5] setindex!(::NCDatasets.CFVariable{Union{Missing, Float32},3,NCDatasets.Variable{Float32,3},NCDatasets.Attributes,NamedTuple{(:fillvalue, :scale_factor, :add_offset, :calendar, :time_origin, :time_factor),Tuple{Float32,Nothing,Nothing,Nothing,Nothing,Nothing}}}, ::Array{Union{Missing, Float32},3}, ::Colon) at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\indexing_in_vars.jl:299
 [6] #_defVar#21(::Dict{String,Any}, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(NCDatasets._defVar), ::NCDataset,
::String, ::Array{Union{Missing, Float32},3}, ::Type, ::Tuple{String,String,String}) at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\variables.jl:256
 [7] #_defVar at .\none:0 [inlined]
 [8] #defVar#18 at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\variables.jl:196 [inlined]
 [9] (::NCDatasets.var"#kw##defVar")(::NamedTuple{(:attrib,),Tuple{Dict{String,Any}}}, ::typeof(defVar), ::NCDataset, ::String, ::Array{Union{Missing, Float32},3}, ::Tuple{String,String,String}) at .\none:0
```

but I get this weird error, even though all variables have the same dimensions... (I checked all of them).

**Comment by Datseris** [comment]
I would really appreicate some help on finding "which" variable has this problem. I've checked every single variable in my dataset and they all have the same size, (`360 x 180 x 231`) (except the dimension variables of course). At the moment I cannot `close` the dataset because I get this error...

**Comment by Datseris** [comment]
In any case, restarting Julia, reloading the dataset, and adding the variables one by one worked for me. I can now load the merged dataset and `close` it, and the error doesn't appear anymore. Therefore, this is certainly a bug from NCDatasets.jl.

**Comment by Datseris** [comment]
Damnit, no! It doesn't work, I can't add variables any more!!! This stupid error
```
ERROR: LoadError: NCDatasets.NetCDFError(-62, "NetCDF: One or more variable
sizes violate format constraints")
```
actually prevents me from _saving_ the dataset with more variables!

**Comment by Alexander-Barth** [comment]
> Yeap, even if I try from another computer and with different names, this functionality is bugged.

Have you had a look here ? 

https://alexander-barth.github.io/NCDatasets.jl/latest/experimental/#Multi-file-support-1
https://alexander-barth.github.io/NCDatasets.jl/latest/dataset/#NCDatasets.NCDataset

Can you confirm that you are trying to aggregated netcdf files over a given dimension?
Or are you trying do to something else?

**Comment by Datseris** [comment]
Hi,

I am not sure if we use the word aggregation for the same meaning, therefore I will explain as explicitly as possible what I am trying to do:

1. I have three `.nc` files, that are part of the same "dataset/campaign" (CERES EBAF). Thse datasets contain fields all of which are defined with respect to the same dimensions.
2. I want to combine these three `.nc` files into one, so that once I load this one file I can access the variables of all three files from one file. **I am not trying to combine two arrays into one array**.
3. I guess the "multifile format" is _not_ what I want, as it tries to aggregate things (notice that I am not sure what "aggregate" means in your context, I use the word "aggregate" to when combinging things to one thing, so I would use it here as well. But I think you use it combine arrays into one array). I don't want to combine arrays, I only want to be able to type `dataset["varname"]` and this to be valid for `"varname"` belonging to any of my three `.nc` files.

The PR #78 achieves this, but it hits the bug I described here.

**Comment by Alexander-Barth** [comment]
By " aggregate netcdf files over a given dimension" I mean, if you have two NetCDF files `file1.nc` and `file2.nc` with a variable `var` of size `(100,101,1)` (lon/lat/time) and you aggregated over the time dimension, you will have a `Dataset` with a variable of the size `(100,101,2)`. 

If I understand you correctly, you want to do something like similar to a `merge(d::AbstractDict, others::AbstractDict...)` (except of NCDataset). The result should be a persistent file or just a in-memory combined representation of all the files?

**Comment by Datseris** [comment]
That is exactly what I want, and I want to write the result in disk (and later on load it properly with `NCDataset()`. 

> (but I do not expect to make such operations today)

Its okay I already did it. Please have a look in the PR #78 because it exactly extents `merge(::Dict, ::Dict)`, what is left is to resolve the bug I describe here (but of course I am not sure of what is the best way to test it).

**Comment by Alexander-Barth** [comment]
I had a shot at this issue in the branch `multifile-merge`.

https://github.com/Alexander-Barth/NCDatasets.jl/blob/multifile-merge/test/test_catarrays.jl#L172

So far I use a special string (the empty string ""), to signal that one should not aggregate over a dimension and all files have to search to find a specific variable. But a better solution would be to encode this in the type of `MFDataset`.

In this branch, it is just a in-memory combined representation of all the files. Nothing is changed on the disk.

**Comment by Datseris** [comment]
Heeeeell yeah!!! this worked, 
```julia
using NCDatasets
CERES1 = datadir("CERES", "CERES_EBAF_TOA.nc")
CERES2 = datadir("CERES", "CERES_EBAF_CLD.nc")
CERES3 = datadir("CERES", "CERES_EBAF_SFC.nc")
all = NCDataset([CERES1, CERES2, CERES3], aggdim = "")
```
did combine all my data into "one file".

I got two comments:

* The `aggdim = ""` should be made something more Julian, e.g. `nothing`.
* How do I actually save the resulting combination file into disk? As I have described, I want to combine all three of my files into one.

**Comment by Alexander-Barth** [comment]
>    The aggdim = "" should be made something more Julian, e.g. nothing.

I agree, that `aggdim = ""`  is not nice. `nothing` is already used for the first record dimension (similar to python https://unidata.github.io/netcdf4-python/netCDF4/index.html#netCDF4.MFDataset.__init__ ). But I am ready to make this breaking change if there is no better solution.

>    How do I actually save the resulting combination file into disk? As I have described, I want to combine all three of my files into one.

Actually, your `merge!` function might already do this! `a` would be an empty NetCDF file and `b` the multifile dataset.

**Comment by Datseris** [comment]
> Actually, your merge! function might already do this! a would be an empty NetCDF file and b the multifile dataset.

Okay, I'll test it but the function still has to be modified because it doesn't take care of dimensions (it doesn't use `defDim`).

**Comment by Alexander-Barth** [comment]
> > Actually, your merge! function might already do this! a would be an empty NetCDF file and b the multifile dataset.
> 
> Okay, I'll test it but the function still has to be modified because it doesn't take care of dimensions (it doesn't use `defDim`).

Thanks, that would be great.
Can you also use Unix line endings for the new source files you create? (I prefer to have the repo consistently with the same line endings)

**Comment by Datseris** [comment]
> Can you also use Unix line endings for the new source files you create? (I prefer to have the repo consistently with the same line endings)

I don't know how to do that.

**Comment by Datseris** [comment]
@Alexander-Barth I confirm that using the updated `merge!` I've just pushed, and your branch of `multifile-merge`, I was able to do what I wanted. Here is the full code that succeeded:

```
using NCDatasets
using DrWatson
@quickactivate :AlbedoProperties

CERES1 = datadir("CERES", "CERES_EBAF_TOA.nc")
CERES2 = datadir("CERES", "CERES_EBAF_CLD.nc")
CERES3 = datadir("CERES", "CERES_EBAF_SFC.nc")

cerescombined = NCDataset([CERES1, CERES2, CERES3], aggdim="")

ceresall = NCDataset(datadir("CERES", "CERES_EBAF.nc"), "c",
            attrib = cerescombined.attrib)

merge!(ceresall, cerescombined)

close(ceresall)
close(cerescombined)

```

**Comment by Alexander-Barth** [comment]
> > Can you also use Unix line endings for the new source files you create? (I prefer to have the repo consistently with the same line endings)
> 
> I don't know how to do that.

It depends on which editor you use, but if it is atom (juno is based on atom), I found these instructions:

https://stackoverflow.com/questions/48630322/atom-editor-convert-line-endings-to-unix

**Comment by Datseris** [comment]
I couldn't find a way to make `merge!` copy the global attributes, because I thought that the only way to define global attributes for a dataset is during its creation, which is why in my code I do:
```
ceresall = NCDataset(datadir("CERES", "CERES_EBAF.nc"), "c",
            attrib = cerescombined.attrib)
```
I'll try to see if it works for passing the attribute structure directly and also add some actual tests so we can merge it in.

---

How should I modify the code for the groups? I honestly know nothing about groups...

**Comment by Alexander-Barth** [comment]
NetCDF `groups` are file within files (or `Dataset`s withing `Dataset`s for `NCDatasets`). Once the group is defined with `defGroup` (if it is not already there) you can call `merge!` recursively on it.


https://www.unidata.ucar.edu/software/netcdf/workshops/2011/groups-types/GroupsIntro.html

**Comment by Datseris** [comment]
the purpose of `merge!` is to transfer keys (and their values) from one set to the other. I don't have access to a dataset with groups. What does `keys()` return to adataset with groups? Does this include groups? Can groups be accessed as keys? And to test this, where does one find a dataset with groups?

**Comment by Alexander-Barth** [comment]
> What does keys() return for a dataset with groups? Does the keys include groups? Can groups be accessed as keys? And to test this, where does one find a dataset with groups?

The function `example_file` that you are using creates already a group. The groups names are accessed via `ds.group` which is a Dict-like object and its keys are the group names. I can try to implement this myself (I hope that I find the time soon). We your able to change the files to unix line endings ?

**Comment by Datseris** [comment]
I think I converted the file endings...? I don't know, I Think I did. I can't know which file endings have different endings though, but for some reason you have this information so I guess feel free to convert what is left...?

Here is what I recommend: merge the `merge!` function before you implement the groups (I don't know groups in order to do this), since adding groups is a non breaking extra feature. Also, I think it will need a bit more thinking because: if I tried to merge some variable `v` from `b` to `a`, I wouldn't expect this variable to end up under a group, even if it was initially under a group in `b`... If you specify the group by key in `merge!` then okay, it makes sense to just copy the entire group, but for other cases at least for me it is not so trivial what should happen. And what if `a` and `b` have a group with the same name, then should merging `v` from `b` to `a` go under the group, if it was originally in the same-name group?

**Comment by Alexander-Barth** [comment]
> I think I converted the file endings...? I don't know, I Think I did. I can't know which file endings have different endings though, but for some reason you have this information so I guess feel free to convert what is left...?

Atom tells you, the line endings: if you see CRLF in the bottom bar, then you are using the DOS convention. If you see LF, then the Unix convention.

The problem which changing the line ending after merge, is that that they create huge diffs (every line of the file is changed). But I belief that all files are have unix line-endings now.

Thanks for the PR.

**Comment by Alexander-Barth** [comment]
I think that there can be a problem with this:

```julia
       cfvar = src[x]
        if x ∈ keys(src.dim) # this is a dimension
            defDim(dest, x, length(cfvar))
        end
```

`length(cfvar)` is the total number of elements, e.g. 110 of an array of 10x11

**Comment by Alexander-Barth** [comment]
I just realized that your merge does not behave as a julia dict merge:

```
  julia> d1 = Dict(1 => 2, 3 => 4);
  
  julia> d2 = Dict(1 => 4, 4 => 5);
  
  julia> merge!(d1, d2);
  
  julia> d1
  Dict{Int64,Int64} with 3 entries:
    4 => 5
    3 => 4
    1 => 4
```

Note that the key 1 gets overwritten. However, you cannot delete a NetCDF variables in a file (as far as I know).

**Comment by Datseris** [comment]
`merge!` works fine even if `a` is in append mode, but skips keys that exists in both exactly because of the reason that you mentioned. From my side there is no reason for this issue to remain open, we provided a way to do what was asked in the original post both in-memory (with the multifiles) as well as on disk (with `merge!`).

**Comment by Alexander-Barth** [comment]
Note that I renamed the `merge!` function `write` to simplify.
The merging functionality is already in `MFDataset`.
