### ISSUE TITLE
Set attributes on dimensions?

### ISSUE THREAD

**Issue by squaregoldfish** [Alexander-Barth/NCDatasets.jl#8]
Is it possible to set attributes on dimensions when creating a netCDF file? I haven't been able to spot it in the docs, but I may have missed it.

If this isn't possible, it should be, especially for readers to understand geographical and time dimensions correctly.

**Comment by Balinus** [comment]
As far as I understand it, you create a variable with the same name as the dimension and attach attributes to the variable associated with the dimension. At least, that's how I understand and use the attributes to read the netCDF files in an automatic way in [ClimateTools.jl](https://github.com/Balinus/ClimateTools.jl).

**Comment by Balinus** [comment]
Nice, thanks for the suggestion! The whole "nc2julia" function is a mess right now. Trying to generalize as much as possible. Will definitely include your suggestion. Cheers!

**Comment by squaregoldfish** [comment]
Thank you!
