### ISSUE TITLE
Is there a way to close all Datasets at one go

### ISSUE THREAD

**Issue by natgeo-wong** [Alexander-Barth/NCDatasets.jl#82]
Just a question:  Is there a way to close all open datasets at one go?  Or must each one be identified?

**Comment by Alexander-Barth** [comment]
All ways to close a NetCDF files are mentioned in the documentation. There is no other way beyond what is mentioned there. It would be nice to use `finalizers` so that Julia's GC can close the file if there are no more reference to it, but this is not possible currently.
