### ISSUE TITLE
Handle CRS

### ISSUE THREAD

**Issue by rafaqz** [Alexander-Barth/NCDatasets.jl#85]
Rs raster package seems to handle netcdf CRS quite cleanly:
https://github.com/rspatial/raster/blob/7fb3a36b6ff0f2943e5314af77939830c6baa2fe/R/netCDFutil.R#L7

It could be good to include something like that here - it first looks for attached crs like Proj or an EPSG code, then falls back to converting the netcdf CRS fields.

The output could be wrapped with GeoFormatTypes.jl `ProjString` or `EPSG` wrapper, so it can be used elsewhere without parsing.

**Comment by Alexander-Barth** [comment]
I agree that it would be nice to support the information in the CRS fields [1]. Note that I have not a direct use of this feature personally (as I use the lon/lat vectors/arrays defined in the NetCDF files), so it is unlikely that I implement this feature myself.

Does this feature require any dependency on a C-library (or any non-julia dependency) installed by the user?

[1] http://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#grid-mappings-and-projections

**Comment by rafaqz** [comment]
It' wont need a library. IBut i would involve dependency on GeoFormatTypes - it's a tiny package just providing type wrappers. You can load ArchGDAL to do things with them if and when you want to.

My use case is for saving arrays originally loaded from netcdf to a tiff or other format in GeoData.jl. I have it working fine for standard Lon/Lat, but projected non-linear dimension vectors need to have the crs to be saved to tiff.

I just figure it might be more useful here than just in GeoData.jl. I can put a PR together.

**Comment by Alexander-Barth** [comment]
> It' wont need a library. But it would involve dependency on GeoFormatTypes - it's a tiny package just providing type wrappers for `WellKnownText`, `EPSG` etc. You can load ArchGDAL to do things with them if and when you want to.

This is indeed a good design choice!

> 
> My use case is for saving arrays originally loaded from netcdf to a tiff or other format in GeoData.jl. I have it working fine for standard Lon/Lat, but projected non-linear dimension vectors need to have the crs to be saved to tiff.
> 
> I just figure it might be more useful here than just in GeoData.jl. I can put a PR together.

That would be great!

**Comment by rafaqz** [comment]
> This is indeed a good design choice!

> Does this feature require any dependency on a C-library (or any non-julia dependency) installed by the user?

I wrote GeoFormatTypes.jl 100% in anticipation of this question :)

**Comment by rafaqz** [comment]
Damn that's GNU licensed, we can't even read it. Maybe also permanently delete this issue.

**Comment by Alexander-Barth** [comment]
OK, as requested, I will close this issue. Feel free to open a new issue.
