### ISSUE TITLE
Memory use loading files

### ISSUE THREAD

**Issue by rafaqz** [Alexander-Barth/NCDatasets.jl#89]
When loading a 2GB netcdf and indexing into part of a `CFVariable` I'm seeing about 6GB memory use - up to 100% memory, and some cache use on top of that.

Is this expected? Do you have any thoughts on workarounds to reduce this?

The performance of NCDatasets is already pretty good, but maybe we can make it better.

**Comment by Alexander-Barth** [comment]
Have a look here: https://github.com/Alexander-Barth/NCDatasets.jl/issues/75
As usual a MWE is useful to clarify which functions you are testing. It reduces also my (guess) work to reproduce a potential issues (see the issue template).

**Comment by rafaqz** [comment]
It's not easy to give you a perfect MWE with private 2GB files, and the behaviour seeming to be quite variable. But I'll try to describe the problem a little more.

```julia
A = NCDatasets.Dataset(path) do ds
    Array(ds["somevar"])
end
```

If I run this sometimes it is fine, but sometime jumps up in memory use. It may just go to 60% then back to 50% where it should be for such a large file. But occasionally it spikes and uses all available memory, then stays there. Often this crashes julia.

Using `load` is probably the answer here, but it would be nice to know what causes this variability.

**Comment by Alexander-Barth** [comment]
A several memory related thinks have changed since. The variability might be related to the julia's garbage collector. If the issue persists, please provide all information from the issue template including a MWE. One could for example create a netCDF file with random data.
