### ISSUE TITLE
Breaking changes ahead

### ISSUE THREAD

**Issue by Alexander-Barth** [Alexander-Barth/NCDatasets.jl#9]
When I started writing NCDatasets, DataArray was the recommended way to store missing values and also used by the packages DataFrames.jl.

There is now a better approach with the missing type [1] (which will be part of Julia 0.7 and is currently an external package for 0.6).  DataFrames.jl now also uses the missing type.

If e.g. `ds` is a NetCDF dataset with the 2D Float32 variable `var`, then
`ds["var"][:,:]` returns currently a `DataArrays.DataArray{Float32,2}`. I propose to change this behaviour and the return `Array{Union{Float32,Missings.Missing},2}` instead.

We could provide additional simple utility function like `nomissing(a)` (which checks that the array contains no missing values and returns a "plain" array of type Array{Float32,2} for the example above) and `nomissing(a,fv)` (which replace all missing values by `fv` and returns a "plain" array).

It seems that when no missing values are present, DataFrames returns directly an "plain" array when a column is indexed. This behaviour could also be implemented but as far as I can see this would not be type stable.

Any suggestion how to deal with the braking change are welcome.

[1] https://docs.julialang.org/en/latest/base/base/#Base.Missing

**Comment by Balinus** [comment]
I don't know what would be the best solution, I'll think about it. I can say though that returning always the same type is important for downstream packages. For example, for mapping purposes I rely on Python's basemap/numpy and I need to convert DataArrays.DataArray{N, T} to "plain" `Array{N, T}`. So having a consistent return type would be simpler I guess (and not only for downstream packages, but you also!).

**Comment by Alexander-Barth** [comment]
Thank you for your feedback! I see too the benefit of having a consistent return type.

**Comment by Alexander-Barth** [comment]
These changes a part of the release 0.2.0.
