### ISSUE TITLE
Freeze in `_nc_check_size_put_vars`

### ISSUE THREAD

**Issue by kpamnany** [Alexander-Barth/NCDatasets.jl#92]
**Describe the bug**

If you accidentally use the wrong dimensions to append to a variable, the call seems to freeze in the `while true` loop in `_nc_check_size_put_vars`. Partial stack trace when you interrupt:
```
signal (2): Interrupt
in expression starting at /central/home/kpamnany/ClimateMachine.jl-alt/experiments/AtmosLES/bomex.jl:551
+ at ./int.jl:53 [inlined]
_nc_check_size_put_vars at /central/home/kpamnany/ClimateMachine.jl-alt/.julia_depot/dev/NCDatasets/src/netcdf_c.jl:863
nc_put_vars at /central/home/kpamnany/ClimateMachine.jl-alt/.julia_depot/dev/NCDatasets/src/netcdf_c.jl:885
setindex! at /central/home/kpamnany/ClimateMachine.jl-alt/.julia_depot/dev/NCDatasets/src/variable.jl:409
setindex! at /central/home/kpamnany/ClimateMachine.jl-alt/.julia_depot/dev/NCDatasets/src/variable.jl:457 [inlined]
setindex! at /central/home/kpamnany/ClimateMachine.jl-alt/.julia_depot/dev/NCDatasets/src/cfvariable.jl:547
```

**To Reproduce**

```julia
using NCDatasets
ds = NCDataset("test.nc", "c")
ds.dim["z"] = 4
ds.dim["time"] = Inf
defVar(ds, "temp", Float64, ("z", "time"))
ds["temp"][:, :, 1] = rand(4)
```

**Expected behavior**

A `BoundsError` or some such exception thrown?

**Environment**

- CentOS Linux 7
- Julia 1.4.1
- NCDatasets version: 0.10.2

**Comment by Alexander-Barth** [comment]
Thanks a lot for your tests case. I helped a lot to quickly locate the issue.

I think that your test case should actually be valid and not return an exception (and certainly not go into an infinite loop) as the following julia code works too:

```
julia> A = zeros(4,1)
4×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0

julia> A[:,:,1] = rand(4)
4-element Array{Float64,1}:
 0.4061176674406306
 0.6179986457653392
 0.21474261922622473
 0.4605486176579232
```

The time dimension is an unlimited dimension so it should be able to grow to fit the data.
