### ISSUE TITLE
Non-automatic convertion of missing values to `missing`

### ISSUE THREAD

**Issue by Datseris** [Alexander-Barth/NCDatasets.jl#97]
Hi there, not sure if this is a bug. If I recall correctly, once a variable is loaded from an NCFile, potentially missing values are equated to Julia's `missing`. I have the following scenario:

```julia
julia> allveg = [datadir("Vegetation", s) for s in readdir(datadir("Vegetation")) if endswith(s, ".nc")];

julia> combined = NCDataset(allveg, aggdim="time");

julia> combined["forestcoverfraction"]
forestcoverfraction (720 × 360 × 19)
  Datatype:    Int8
  Dimensions:  lon × lat × time
  Attributes:
   long_name            = Forest Cover Fraction
   units                = percent
   missing_value        = 127
   _fillvalue           = 127
   valid_min            = 0
   valid_max            = 100
   comment              = This is the mean per grid cell fraction of vegetation
of type forest

julia> Array(combined["forestcoverfraction"])[:, :, 1]
720×360 Array{Int8,2}:
 127  127  127  127  127  127  127  127  …  127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127  …  127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127  …  127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127  …  127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127  …  127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
 127  127  127  127  127  127  127  127     127  127  127  127  127  127  127
   ⋮                        ⋮            ⋱              ⋮
```

The numbers above should have been `missing` instead of `127` (and this would make sense with the dataset I try to load).

Potential reasons this happened:

* `_fillvalue` is not capitalized as `_Fillvalue`
* fill value and missing value are equals

?

**Comment by Alexander-Barth** [comment]
This is indeed a typo in your NetCDF file.
The correct capitalization of the fill value attribute is `_FillValue`:
http://cf-metadata.github.io/#attribute-appendix

**Comment by joanantichna** [comment]
Hello, I'm very new to Julia, but have a bit of experience in Python, and extremely new to GitHub, so sorry in advance if i'm just not placing my comment in the aproppiate place. I'm trying to use the __FillValue_ functionality as to fill the _missing_value_ of a given NETCDF  file pretty much in the same way @Datseris was operating, but it is not working for me so far.
The context is the following:
I have a set of NETCDF files. Each file has many variables and each variable has the same attributes. For simplification i will explain the problem onto just one, randomly taken, variable called "u", refering to some velocity component. This variable has 3 attributes defined, one of them being "missing_value". What i am trying to do is to add a new attribute that would fill the missing values with the word "missing" as i've seen is the only way to correctly handel such data type to avoid spreading errors. 

The way i do it, i belive, is simple:

```Julia
using NCDatasets
for filename in glob("*.nc","path_to_directory_of_files")      
  ds = NCDataset(filename, "a")
  u_data=ds["u"] 
  u_data.attrib["_FillValue"]="missing"
  break # As to only apply it to the first file ( when it works i will delet this break )
 end 
```

Nevertheless, even if this Attribute-adding is well done, as i can see by just calling the 

"_print(u_data.attrib)_" and observing that the __FillValue_ feature is there now, the missing values, which have been defined as a Number value=-1.0e30 are not converted to the "_missing_" type. Even if redefining the __FillValue_ to another value it's still not working. 

Do you know what could be happening? I've tried many different ways of typing "missing" so as to avoid it being a typo but none have worked so far.

Pd: As said before, i'm new to git-hub, but also to programing in general and this is the first time i use it to ask something so if there is information needed that is not here i can be more explicit.
Thanks in advance

**Comment by Alexander-Barth** [comment]
Welcome to the community!

I think there is a confusion between the string "missing" and the type missing (without quotes).

In any, case `u_data.attrib["_FillValue"]` should be a value of the same type as the variable `u`. If `u` is a double (or Float64 for julia) and if `-1.0e30` is the value representing missing data, you should rather use 

```julia
 u_data.attrib["_FillValue"] = -1.0e30
```

Do not forget to close the netCDF file with `close(ds)`. It might be useful for you to have a look at  the documentation.
